use super::resolvers_from;

#[test]
fn system_resolvers_follow_resolv_conf_and_keep_two_ipv4_servers() {
    let text = "# generated by Docker\nnameserver 127.0.0.11\n\
                    nameserver 2001:db8::1\nnameserver 1.1.1.1 # fallback\n\
                    nameserver 127.0.0.11\nnameserver 9.9.9.9\n";
    assert_eq!(resolvers_from(text), vec!["127.0.0.11", "1.1.1.1"]);
    assert!(resolvers_from("search example.test\nnameserver ::1\n").is_empty());
}
