#!/usr/bin/env python3
"""Generate the public route index from the router and shared wire contract."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from tools import ROOT
from tools.protocol import wire_contract

OUTPUT = ROOT / 'docs/src/reference/api-routes.md'


@dataclass(frozen=True)
class Route:
    method: str
    path: str
    handler: str
    scope: str


def matching_close(text: str, open_at: int) -> int:
    """Find a call's closing parenthesis while ignoring strings and comments."""

    depth = 0
    quote: str | None = None
    escaped = False
    comment = False
    i = open_at
    while i < len(text):
        char = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ''
        if comment:
            if char == '\n':
                comment = False
        elif quote:
            if escaped:
                escaped = False
            elif char == '\\':
                escaped = True
            elif char == quote:
                quote = None
        elif char == '/' and nxt == '/':
            comment = True
            i += 1
        elif char in '\'"':
            quote = char
        elif char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return len(text)


def api_routes(files: dict[Path, str] | None = None) -> list[Route]:
    if files is None:
        files = {
            ROOT / name: (ROOT / name).read_text(encoding='utf-8')
            for name in ('slopd/src/shared/protocol.rs', 'slopd/src/api/router.rs')
        }
    routes: list[Route] = []
    wire_paths: dict[str, str] = {}
    route_paths: dict[str, str] = {}
    for path, text in files.items():
        if path != ROOT / 'slopd/src/shared/protocol.rs':
            continue
        for match in re.finditer(
            r"\bconst\s+([A-Z][A-Z0-9_]*)\s*:\s*&str\s*=\s*['\"]([^'\"]+)['\"]",
            text,
        ):
            wire_paths[match.group(1)] = match.group(2)
        routes_block = re.search(r'pub\(crate\)\s+mod\s+routes\s*\{(.*?)\n\}', text, re.DOTALL)
        if routes_block:
            for match in re.finditer(
                r"\bconst\s+([A-Z][A-Z0-9_]*)\s*:\s*&str\s*=\s*['\"]([^'\"]+)['\"]",
                routes_block.group(1),
            ):
                route_paths[match.group(1)] = match.group(2)
    method_pattern = re.compile(r'\b(get|post|put|delete|patch|head|options|trace)\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)')
    for path, text in files.items():
        if path != ROOT / 'slopd/src/api/router.rs':
            continue
        for match in re.finditer(r'\.route\s*\(', text):
            end = matching_close(text, text.find('(', match.start()))
            body = text[match.end() : end]
            path_match = re.search(r"['\"]([^'\"]+)['\"]", body)
            path_value = path_match.group(1) if path_match else None
            if path_value is None:
                route_const = re.search(r'routes::([A-Z][A-Z0-9_]*)', body)
                if route_const:
                    path_value = route_paths.get(route_const.group(1))
                else:
                    const_match = re.search(r'shared::protocol::([A-Z][A-Z0-9_]*)', body)
                    path_value = wire_paths.get(const_match.group(1)) if const_match else None
            if path_value is None:
                raise ValueError(
                    f'unresolved API route path at {path.relative_to(ROOT)}:{text.count(chr(10), 0, match.start()) + 1}'
                )
            before = text[: match.start()]
            # Route families own middleware access; fail rather than silently label
            # a new family as accessible to scoped grants.
            functions = list(re.finditer(r'\bfn\s+(\w+)\s*\(', before))
            family = functions[-1].group(1) if functions else None
            if family not in {'root_routes', 'scoped_routes', 'shared_routes', 'snapshot_routes'}:
                raise ValueError(f'unknown API route family: {family}')
            scope = 'root-only' if family == 'root_routes' else 'scoped'
            for method_match in method_pattern.finditer(body):
                routes.append(
                    Route(
                        method=method_match.group(1).upper(),
                        path=path_value,
                        handler=method_match.group(2),
                        scope=scope,
                    )
                )
    return sorted(routes, key=lambda r: (r.path, r.method))


def render() -> str:
    payloads = {
        (method, route['path']): types
        for route in wire_contract.load()['protocol']['http']['routes'].values()
        for method, types in route['protobuf'].items()
    }
    lines = [
        '<!-- Generated by tools/docs/api_docs.py. Do not edit. -->',
        '# API route inventory',
        '',
        'Find endpoint paths and message types here. See the [API contract](api.md)',
        'for encoding, errors, and authorization. `Empty` means no body.',
        '',
        'Route access groups describe middleware placement. `scoped` does not promise',
        'access to every scoped credential: handlers also enforce permissions, and',
        'session creation requires root. See [Authorization](api.md#authorization).',
        '',
    ]
    routes = api_routes()
    discovered = {(route.method, route.path) for route in routes if route.path != '/ws'}
    if discovered != payloads.keys():
        raise ValueError(f'HTTP route inventory differs from wire contract: {discovered ^ payloads.keys()}')
    families = {
        'sessions': 'Sessions and grants',
        'grants': 'Sessions and grants',
        'tasks': 'Tasks and workers',
        'workers': 'Tasks and workers',
        'projects': 'Projects and worktrees',
        'worktrees': 'Projects and worktrees',
        'templates': 'Agent templates',
        'config': 'Configuration and state',
        'settings': 'Configuration and state',
        'state': 'Configuration and state',
        'presets': 'Configuration and state',
        'browse': 'Workspace and files',
        'read': 'Workspace and files',
        'files': 'Workspace and files',
        'git': 'Workspace and files',
        'image': 'Workspace and files',
        'search': 'Workspace and files',
        'highlight': 'Workspace and files',
        'library': 'Library and actions',
        'run': 'Library and actions',
        'file-action': 'Library and actions',
        'open-apps': 'Library and actions',
    }
    groups: dict[str, list[Route]] = {}
    for route in routes:
        if route.path == '/ws':
            continue
        parts = route.path.split('/')
        if len(parts) < 3 or parts[1] != 'api':
            raise ValueError(f'HTTP route must have an /api/<family> path: {route.path}')
        family = parts[2]
        groups.setdefault(families.get(family, 'Integrations and diagnostics'), []).append(route)
    for family, entries in groups.items():
        lines.extend(
            [
                f'## {family}',
                '',
                '| Method | Path | Route access group | Request body | Response |',
                '| --- | --- | --- | --- | --- |',
            ]
        )
        for route in entries:
            request, response = payloads[(route.method, route.path)]
            lines.append(f'| `{route.method}` | `{route.path}` | `{route.scope}` | `{request}` | `{response}` |')
        lines.append('')
    lines.extend(
        [
            '## WebSocket',
            '',
            '`GET /ws` upgrades to a WebSocket connection. See the',
            '[WebSocket contract](api.md#websocket) for the handshake and subprotocol.',
            '',
            '| Direction | Message |',
            '| --- | --- |',
            '| Client → daemon | `ClientMessage` |',
            '| Daemon → client | `Event` |',
        ]
    )
    return '\n'.join(lines) + '\n'


def main() -> None:
    OUTPUT.write_text(render(), encoding='utf-8')
    print(OUTPUT)


if __name__ == '__main__':
    main()
