#!/usr/bin/env python3
"""Generate the public route index from the router and shared wire contract."""

from __future__ import annotations

from tools import ROOT
from tools.docs.reference import Route
from tools.docs.reference import api_routes
from tools.protocol import wire_contract

OUTPUT = ROOT / 'docs/src/reference/api-routes.md'


def render() -> str:
    payloads = {
        (method, route['path']): types
        for route in wire_contract.load()['protocol']['http']['routes'].values()
        for method, types in route['protobuf'].items()
    }
    lines = [
        '<!-- Generated by tools/docs/api_docs.py. Do not edit. -->',
        '# API route inventory',
        '',
        'Find endpoint paths and message types here. See the [API contract](api.md)',
        'for encoding, errors, and authorization. `Empty` means no body.',
        '',
        'Route access groups describe middleware placement. `scoped` does not promise',
        'access to every scoped credential: handlers also enforce permissions, and',
        'session creation requires root. See [Authorization](api.md#authorization).',
        '',
    ]
    routes = api_routes()
    discovered = {(route.method, route.path) for route in routes if route.path != '/ws'}
    if discovered != payloads.keys():
        raise ValueError(f'HTTP route inventory differs from wire contract: {discovered ^ payloads.keys()}')
    families = {
        'sessions': 'Sessions and grants',
        'grants': 'Sessions and grants',
        'tasks': 'Tasks and workers',
        'workers': 'Tasks and workers',
        'projects': 'Projects and worktrees',
        'worktrees': 'Projects and worktrees',
        'templates': 'Agent templates',
        'config': 'Configuration and state',
        'settings': 'Configuration and state',
        'state': 'Configuration and state',
        'presets': 'Configuration and state',
        'browse': 'Workspace and files',
        'read': 'Workspace and files',
        'files': 'Workspace and files',
        'git': 'Workspace and files',
        'image': 'Workspace and files',
        'search': 'Workspace and files',
        'highlight': 'Workspace and files',
        'library': 'Library and actions',
        'run': 'Library and actions',
        'file-action': 'Library and actions',
        'open-apps': 'Library and actions',
    }
    groups: dict[str, list[Route]] = {}
    for route in routes:
        if route.path == '/ws':
            continue
        parts = route.path.split('/')
        if len(parts) < 3 or parts[1] != 'api':
            raise ValueError(f'HTTP route must have an /api/<family> path: {route.path}')
        family = parts[2]
        groups.setdefault(families.get(family, 'Integrations and diagnostics'), []).append(route)
    for family, entries in groups.items():
        lines.extend(
            [
                f'## {family}',
                '',
                '| Method | Path | Route access group | Request body | Response |',
                '| --- | --- | --- | --- | --- |',
            ]
        )
        for route in entries:
            request, response = payloads[(route.method, route.path)]
            lines.append(f'| `{route.method}` | `{route.path}` | `{route.scope}` | `{request}` | `{response}` |')
        lines.append('')
    lines.extend(
        [
            '## WebSocket',
            '',
            '`GET /ws` upgrades to a WebSocket connection. See the',
            '[WebSocket contract](api.md#websocket) for the handshake and subprotocol.',
            '',
            '| Direction | Message |',
            '| --- | --- |',
            '| Client → daemon | `ClientMessage` |',
            '| Daemon → client | `Event` |',
        ]
    )
    return '\n'.join(lines) + '\n'


def main() -> None:
    OUTPUT.write_text(render(), encoding='utf-8')
    print(OUTPUT)


if __name__ == '__main__':
    main()
