//! The generated project-root runtime manifest exposed to opted-in agents.
//!
//! The file is deliberately project-scoped rather than session-scoped: every agent that shares
//! a project sees the same workspace and collaborator picture, while the daemon still controls
//! which sessions get the read-only overlay and discovery breadcrumb.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{bail, Context, Result};

use crate::config::{Config, DnsConfig, Limits, MountMode, ProjectCfg, SessionCfg};
use crate::session::{SessionView, State};

pub const FILE_NAME: &str = "SLOPWORLD.md";

const GENERATED_MARKER: &str = "<!-- Generated by SlopWorld; do not edit or commit. -->";
const GIT_MARKER_PREFIX: &str = "# SlopWorld generated runtime manifest: ";

/// Writes the project manifest and makes it invisible to ordinary Git status output. A project
/// that already owns a real SLOPWORLD.md is refused rather than silently hidden or overwritten.
pub fn prepare(
    dir: &Path,
    cfg: &Config,
    project: &ProjectCfg,
    sessions: &[SessionView],
) -> Result<PathBuf> {
    let path = dir.join(FILE_NAME);
    ensure_writable_generated_target(&path)?;

    ensure_git_excluded(dir)?;
    let text = render(cfg, project, sessions);
    write_atomic(&path, &text).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// Removes only a file and Git exclusion line previously created by SlopWorld. User-owned files
/// and user-authored ignore rules are left alone.
pub fn remove(dir: &Path) -> Result<()> {
    let path = dir.join(FILE_NAME);
    if is_generated(&path) {
        std::fs::remove_file(&path).with_context(|| format!("removing {}", path.display()))?;
    }
    remove_git_exclude(dir)
}

pub fn is_generated(path: &Path) -> bool {
    !std::fs::symlink_metadata(path)
        .map(|m| m.file_type().is_symlink())
        .unwrap_or(false)
        && std::fs::read_to_string(path)
            .map(|text| text.starts_with(GENERATED_MARKER))
            .unwrap_or(false)
}

fn ensure_writable_generated_target(path: &Path) -> Result<()> {
    let Ok(meta) = std::fs::symlink_metadata(path) else {
        return Ok(());
    };
    if meta.file_type().is_symlink() {
        bail!(
            "{} is a symlink; remove or rename it before enabling the SlopWorld manifest",
            path.display()
        );
    }
    if !meta.is_file() {
        bail!(
            "{} exists but is not a regular file; remove or rename it before enabling the SlopWorld manifest",
            path.display()
        );
    }
    if !is_generated(path) {
        bail!(
            "{} already exists; SlopWorld will not overwrite a project-owned file",
            path.display()
        );
    }
    Ok(())
}

fn render(cfg: &Config, project: &ProjectCfg, sessions: &[SessionView]) -> String {
    render_with_template(
        cfg,
        project,
        sessions,
        &cfg.daemon.instructions.template,
        &cfg.daemon.instructions.mount_path,
    )
}

/// Render a document with a caller-supplied template. The preview endpoint uses this to show
/// unsaved edits while the normal writer above uses the durable daemon configuration.
pub fn preview(
    cfg: &Config,
    project: &ProjectCfg,
    sessions: &[SessionView],
    template: &str,
    mount_path: &str,
) -> String {
    render_with_template(cfg, project, sessions, template, mount_path)
}

fn render_with_template(
    cfg: &Config,
    project: &ProjectCfg,
    sessions: &[SessionView],
    template: &str,
    mount_path: &str,
) -> String {
    let runtime_context = render_runtime_context(cfg, project, sessions);
    let body = render_template(template, project, mount_path, &runtime_context);
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(&body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn render_template(
    template: &str,
    project: &ProjectCfg,
    mount_path: &str,
    runtime: &str,
) -> String {
    let values = [
        ("runtime_context", runtime),
        ("project", project.name.as_str()),
        ("mount_path", mount_path),
        ("file", FILE_NAME),
    ];
    render_values(template, &values)
}

/// Render the discovery prompt without exposing the full runtime snapshot. The prompt is a
/// small, stable surface by design: it can point at the generated file without growing with the
/// project's live session list.
pub fn render_breadcrumb(template: &str, project: &str, mount_path: &str) -> String {
    let values = [
        ("project", project),
        ("mount_path", mount_path),
        ("file", FILE_NAME),
    ];
    render_values(template, &values)
}

fn render_values(template: &str, values: &[(&str, &str)]) -> String {
    let mut out = String::with_capacity(template.len());
    let mut rest = template;
    while let Some(start) = rest.find("{{") {
        let Some(end_rel) = rest[start + 2..].find("}}") else {
            break;
        };
        let end = start + 2 + end_rel;
        out.push_str(&rest[..start]);
        let key = rest[start + 2..end].trim();
        if let Some((_, value)) = values.iter().find(|(name, _)| *name == key) {
            out.push_str(value);
        } else {
            out.push_str(&rest[start..end + 2]);
        }
        rest = &rest[end + 2..];
    }
    out.push_str(rest);
    out
}

fn render_runtime_context(cfg: &Config, project: &ProjectCfg, sessions: &[SessionView]) -> String {
    let mut out = String::new();
    out.push_str("# SlopWorld runtime context\n\n");
    out.push_str(
        "> This file is generated and read-only inside agent sandboxes. It is a runtime snapshot, not project instructions.\n\n",
    );
    out.push_str(&format!(
        "Generated at Unix time `{}`.\n\n",
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
    ));

    out.push_str("## Workspace\n\n");
    out.push_str(&format!("- Project: {}\n", code(&project.name)));
    out.push_str(&format!(
        "- Working directory: {}\n",
        code(&format!("/mnt/{}", project.name))
    ));
    out.push_str(
        "- Agents in this project share the same working tree unless their configuration explicitly says otherwise. Coordinate edits and do not assume isolated Git state.\n",
    );

    out.push_str("\n## Sandbox\n\n");
    let project_presets = std::iter::once("global".to_string())
        .chain(project.sandbox.iter().cloned())
        .collect::<Vec<_>>();
    out.push_str(&format!(
        "- Project sandbox presets: {}\n",
        list(&project_presets)
    ));
    let default_session = SessionCfg {
        project: project.name.clone(),
        ..Default::default()
    };
    out.push_str(&format!(
        "- Project network default: {}\n",
        network(cfg.network_of(&default_session, project))
    ));
    out.push_str(&format!(
        "- Project DNS: {}\n",
        dns(cfg.dns_of(&default_session, project))
    ));
    out.push_str(&format!(
        "- Project resource limits: {}\n",
        limits(project.limits)
    ));
    out.push_str(
        "- The project directory is the main writable workspace; additional mounts and per-agent overrides are listed below.\n",
    );

    out.push_str("\n## Agents\n\n");
    out.push_str("| Agent | Command | State | Network | Workspace mount |\n| --- | --- | --- | --- | --- |\n");
    let mut agents = cfg
        .sessions
        .iter()
        .filter(|session| session.project == project.name)
        .collect::<Vec<_>>();
    agents.sort_by(|a, b| a.name.cmp(&b.name));
    if agents.is_empty() {
        out.push_str("No configured agents.\n");
    }
    for session in agents {
        let view = sessions.iter().find(|view| view.name == session.name);
        let command = cfg.command_name(session);
        let state = view.map(|view| state_name(view.state)).unwrap_or("down");
        let effective_network = network(cfg.network_of(session, project));
        let mount = primary_mount(session, project);
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            code(&session.name),
            code(if command.is_empty() {
                "custom command"
            } else {
                &command
            }),
            state,
            effective_network,
            mount
        ));

        let presets = cfg.sandbox_of(session, project);
        out.push_str(&format!(
            "\n  `{}` sandbox presets: {}. Limits: {}.\n",
            one_line(&session.name),
            list(&presets),
            limits(cfg.limits_of(session, project))
        ));
        let escapes = preset_escapes(&presets);
        if !escapes.is_empty() {
            out.push_str(&format!(
                "  Host-reaching capabilities declared by presets: {}.\n",
                list(&escapes)
            ));
        }
        for mount in &session.mounts {
            if mount.project == project.name {
                continue;
            }
            out.push_str(&format!(
                "  Additional mount: {} at {}.\n",
                code(&format!("/mnt/{}", mount.project)),
                mount_mode(mount.mode)
            ));
        }
    }

    out.push_str("\n## Coordination\n\n");
    out.push_str(
        "- `SLOPWORLD_SESSION` identifies the current agent to SlopWorld.\n- If `slopctl` is installed and this sandbox has daemon credentials and network reachability, use it for structured coordination:\n",
    );
    out.push_str("  - `slopctl peers`\n");
    out.push_str("  - `slopctl inbox`\n");
    out.push_str("  - `slopctl delegate AGENT \"task\"`\n");
    out.push_str("  - `slopctl spawn [--durable] PARENT \"task\"` (root only)\n");
    out.push_str("  - `slopctl wait ID`\n");
    out.push_str("  - `slopctl accept ID`, `slopctl progress ID \"note\"`\n");
    out.push_str("  - `slopctl finish ID \"result\"` or `slopctl fail ID \"reason\"`\n");
    out.push_str(
        "- Delegate once, keep the returned task ID, and use `slopctl wait ID` for the result. `task`, `inbox`, and `status` are for inspection, not a replacement for `wait`.\n",
    );
    out.push_str(
        "- Peer and task information can change after this snapshot; use `slopctl` for the live answer when available.\n",
    );
    out
}

fn primary_mount(session: &SessionCfg, project: &ProjectCfg) -> &'static str {
    match session
        .mounts
        .iter()
        .find(|mount| mount.project == project.name)
        .map(|mount| mount.mode)
        .unwrap_or(MountMode::Rw)
    {
        MountMode::Ro => "read-only",
        MountMode::Rw => "read-write",
    }
}

fn preset_escapes(names: &[String]) -> Vec<String> {
    let table = crate::presets::table();
    names
        .iter()
        .filter(|name| {
            table
                .sandbox(name)
                .is_some_and(|preset| !preset.escapes.trim().is_empty())
        })
        .cloned()
        .collect()
}

fn state_name(state: State) -> &'static str {
    match state {
        State::Down => "down",
        State::Working => "working",
        State::Waiting => "waiting",
        State::Idle => "idle",
    }
}

fn network(mode: crate::config::NetworkMode) -> &'static str {
    match mode {
        crate::config::NetworkMode::None => "none (no network)",
        crate::config::NetworkMode::Private => {
            "private (outbound via pasta; no host-local loopback)"
        }
        crate::config::NetworkMode::Host => "host (host network)",
    }
}

fn dns(config: DnsConfig) -> String {
    match config {
        DnsConfig::Resolved => "system resolver".into(),
        DnsConfig::Servers { servers } => format!(
            "explicit servers {}",
            list(&servers.iter().map(ToString::to_string).collect::<Vec<_>>())
        ),
    }
}

fn limits(limits: Limits) -> String {
    let mut values = Vec::new();
    if let Some(value) = limits.memory_mb {
        values.push(format!("memory {value} MiB"));
    }
    if let Some(value) = limits.pids {
        values.push(format!("processes/threads {value}"));
    }
    if let Some(value) = limits.nofile {
        values.push(format!("open files {value}"));
    }
    if let Some(value) = limits.cpu_pct {
        values.push(format!("CPU {value}%"));
    }
    if values.is_empty() {
        "none".into()
    } else {
        values.join(", ")
    }
}

fn mount_mode(mode: MountMode) -> &'static str {
    match mode {
        MountMode::Ro => "read-only",
        MountMode::Rw => "read-write",
    }
}

fn list(items: &[String]) -> String {
    if items.is_empty() {
        return "none".into();
    }
    items
        .iter()
        .map(|item| code(item))
        .collect::<Vec<_>>()
        .join(", ")
}

fn code(value: &str) -> String {
    format!("`{}`", one_line(value).replace('`', "'"))
}

fn one_line(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_control() { ' ' } else { ch })
        .collect::<String>()
        .trim()
        .to_string()
}

fn git_context(dir: &Path) -> Option<(PathBuf, String)> {
    let root = git_output(dir, &["rev-parse", "--show-toplevel"])?;
    let root = PathBuf::from(root.trim());
    let git_path = git_output(dir, &["rev-parse", "--git-path", "info/exclude"])?;
    let git_path = PathBuf::from(git_path.trim());
    let exclude = if git_path.is_absolute() {
        git_path
    } else {
        dir.join(git_path)
    };
    let canonical_dir = std::fs::canonicalize(dir).unwrap_or_else(|_| dir.to_path_buf());
    let canonical_root = std::fs::canonicalize(&root).unwrap_or(root);
    let relative = canonical_dir.strip_prefix(&canonical_root).ok()?;
    let relative = relative.to_string_lossy().replace('\\', "/");
    let pattern = if relative.is_empty() {
        format!("/{FILE_NAME}")
    } else {
        format!("/{relative}/{FILE_NAME}")
    };
    Some((exclude, pattern))
}

fn git_output(dir: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn git_ignores(dir: &Path) -> bool {
    Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(["check-ignore", "-q", "--no-index", "--"])
        .arg(FILE_NAME)
        .status()
        .is_ok_and(|status| status.success())
}

fn ensure_git_excluded(dir: &Path) -> Result<()> {
    let Some((path, pattern)) = git_context(dir) else {
        return Ok(());
    };
    if git_ignores(dir) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("making {}", parent.display()))?;
    }
    let mut text = std::fs::read_to_string(&path).unwrap_or_default();
    let marker = format!("{GIT_MARKER_PREFIX}{pattern}");
    if text.lines().any(|line| line == marker) {
        return Ok(());
    }
    if !text.is_empty() && !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&marker);
    text.push('\n');
    text.push_str(&pattern);
    text.push('\n');
    write_atomic(&path, &text).with_context(|| format!("updating {}", path.display()))
}

fn remove_git_exclude(dir: &Path) -> Result<()> {
    let Some((path, pattern)) = git_context(dir) else {
        return Ok(());
    };
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Ok(());
    };
    let marker = format!("{GIT_MARKER_PREFIX}{pattern}");
    let mut lines = text.lines().peekable();
    let mut kept = String::new();
    while let Some(line) = lines.next() {
        if line == marker && lines.peek().is_some_and(|next| *next == pattern) {
            lines.next();
            continue;
        }
        kept.push_str(line);
        kept.push('\n');
    }
    if kept == text {
        return Ok(());
    }
    if !text.ends_with('\n') {
        kept.pop();
    }
    write_atomic(&path, &kept).with_context(|| format!("updating {}", path.display()))
}

fn write_atomic(path: &Path, text: &str) -> std::io::Result<()> {
    let tmp = path.with_file_name(format!(
        ".{}.tmp-{}",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or(FILE_NAME),
        std::process::id()
    ));
    std::fs::write(&tmp, text)?;
    std::fs::rename(tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, ProjectCfg};

    #[test]
    fn renders_runtime_context_without_host_paths_or_tokens() {
        let cfg = Config::default();
        let project = ProjectCfg {
            name: "repo".into(),
            dir: "/home/alice/repo".into(),
            ..Default::default()
        };
        let text = render(&cfg, &project, &[]);
        assert!(text.contains("/mnt/repo"));
        assert!(text.contains("README.md"));
        assert!(text.contains("slopctl peers"));
        assert!(text.contains("slopctl spawn [--durable] PARENT"));
        assert!(text.contains("slopctl wait ID"));
        assert!(!text.contains("/home/alice/repo"));
        assert!(!text.contains("endpoint.toml"));
    }

    #[test]
    fn preview_expands_instruction_variables_and_preserves_unknown_ones() {
        let cfg = Config::default();
        let project = ProjectCfg {
            name: "repo".into(),
            dir: "/home/alice/repo".into(),
            ..Default::default()
        };
        let text = preview(
            &cfg,
            &project,
            &[],
            "# {{ project }}\nMount: `{{ mount_path }}`\nFile: {{ file }}\n{{ runtime_context }}\n{{ future_variable }}",
            "docs/SLOPWORLD.md",
        );

        assert!(text.starts_with(&format!("{GENERATED_MARKER}\n# repo\n")));
        assert!(text.contains("Mount: `docs/SLOPWORLD.md`"));
        assert!(text.contains("File: SLOPWORLD.md"));
        assert!(text.contains("# SlopWorld runtime context"));
        assert!(text.contains("{{ future_variable }}"));
    }

    #[test]
    fn breadcrumb_expands_stable_variables_and_preserves_unknown_ones() {
        assert_eq!(
            render_breadcrumb(
                "Read {{ mount_path }} for {{ project }} ({{ file }}); {{ future }}",
                "repo",
                "docs/SLOPWORLD.md",
            ),
            "Read docs/SLOPWORLD.md for repo (SLOPWORLD.md); {{ future }}"
        );
    }

    #[test]
    fn generated_marker_is_recognized() {
        let path =
            std::env::temp_dir().join(format!("slopworld-manifest-test-{}", std::process::id()));
        std::fs::write(&path, format!("{GENERATED_MARKER}\n# body\n")).unwrap();
        assert!(is_generated(&path));
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn prepare_excludes_and_remove_cleans_a_nested_project_manifest() {
        let root = std::env::temp_dir().join(format!(
            "slopworld-manifest-git-test-{}",
            uuid::Uuid::new_v4()
        ));
        let dir = root.join("nested");
        std::fs::create_dir_all(&dir).unwrap();
        let init = Command::new("git")
            .args(["-C", root.to_str().unwrap(), "init", "-q"])
            .status()
            .unwrap();
        assert!(init.success());

        let cfg = Config::default();
        let project = ProjectCfg {
            name: "repo".into(),
            dir: dir.to_string_lossy().into_owned(),
            ..Default::default()
        };
        let path = prepare(&dir, &cfg, &project, &[]).unwrap();
        assert!(is_generated(&path));
        let ignored = Command::new("git")
            .args([
                "-C",
                dir.to_str().unwrap(),
                "check-ignore",
                "-q",
                "--no-index",
                "--",
                FILE_NAME,
            ])
            .status()
            .unwrap();
        assert!(ignored.success());

        remove(&dir).unwrap();
        assert!(!path.exists());
        let exclude = git_context(&dir).unwrap().0;
        let exclude_text = std::fs::read_to_string(exclude).unwrap();
        assert!(!exclude_text.contains(FILE_NAME));
        std::fs::remove_dir_all(root).unwrap();
    }
}
