// <auto-generated />
// Source: protocol/wire.yaml; regenerate with `make api-contract`.
#![allow(dead_code)]

#[macro_export]
macro_rules! wire_enum {
    ($ty:ty, { $($variant:path => $value:path),+ $(,)? }) => {
        impl serde::Serialize for $ty {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where S: serde::Serializer {
                let value = match self {
                    $($variant => $value,)+
                };
                serializer.serialize_str(value)
            }
        }
        impl<'de> serde::Deserialize<'de> for $ty {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where D: serde::Deserializer<'de> {
                let value = <String as serde::Deserialize>::deserialize(deserializer)?;
                $(if value == $value { return Ok($variant); })+
                Err(<D::Error as serde::de::Error>::unknown_variant(&value, &[]))
            }
        }
    };
}

#[macro_export]
macro_rules! wire_event_tag {
    (Capabilities) => {
        $crate::wire::events::CAPABILITIES
    };
    (Sessions) => {
        $crate::wire::events::SESSIONS
    };
    (Projects) => {
        $crate::wire::events::PROJECTS
    };
    (Library) => {
        $crate::wire::events::LIBRARY
    };
    (Screen) => {
        $crate::wire::events::SCREEN
    };
    (Usage) => {
        $crate::wire::events::USAGE
    };
    (Audio) => {
        $crate::wire::events::AUDIO
    };
    (Jukebox) => {
        $crate::wire::events::JUKEBOX
    };
}

#[macro_export]
macro_rules! wire_event_serialize {
    ($ty:ty, { $( $variant:ident { $( $field:ident ),+ $(,)? } ),+ $(,)? }) => {
        impl serde::Serialize for $ty {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where S: serde::Serializer {
                use serde::ser::SerializeStruct;
                let mut out = serializer.serialize_struct(stringify!($ty), 2)?;
                match self {
                    $(Self::$variant { $( $field ),+ } => {
                        out.serialize_field("t", $crate::wire_event_tag!($variant))?;
                        $(out.serialize_field(stringify!($field), $field)?;)+
                    }),+
                }
                out.end()
            }
        }
    };
}

#[macro_export]
macro_rules! wire_client_msg_tag {
    (Redraw) => {
        $crate::wire::messages::REDRAW
    };
    (Sub) => {
        $crate::wire::messages::SUB
    };
    (Unsub) => {
        $crate::wire::messages::UNSUB
    };
    (Keys) => {
        $crate::wire::messages::KEYS
    };
    (Resize) => {
        $crate::wire::messages::RESIZE
    };
    (Scroll) => {
        $crate::wire::messages::SCROLL
    };
    (Mouse) => {
        $crate::wire::messages::MOUSE
    };
    (Paste) => {
        $crate::wire::messages::PASTE
    };
    (Breadcrumb) => {
        $crate::wire::messages::BREADCRUMB
    };
    (Audio) => {
        $crate::wire::messages::AUDIO
    };
}

#[macro_export]
macro_rules! wire_client_msg_payload {
    ($value:ident, strip_tag) => {{
        let mut payload = $value;
        payload
            .as_object_mut()
            .expect("websocket message tag came from a JSON object")
            .remove("t");
        payload
    }};
    ($value:ident) => {
        $value
    };
}

#[macro_export]
macro_rules! wire_client_msg_construct {
    ($variant:ident, $req:ident, { $( $field:ident ),+ $(,)? }) => {
        Self::$variant { $( $field: $req.$field ),+ }
    };
    ($variant:ident, $req:ident) => { Self::$variant($req) };
}

#[macro_export]
macro_rules! wire_client_msg_deserialize {
    (
        $ty:ty, {
            $(
                $variant:ident
                $( { $( $field:ident ),+ $(,)? } )?
                => $payload:ty $( [ $mode:ident ] )?
            ),+ $(,)?
        }
    ) => {
        impl<'de> serde::Deserialize<'de> for $ty {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where D: serde::Deserializer<'de> {
                use serde::de::Error;
                let value = serde_json::Value::deserialize(deserializer)?;
                let tag = value
                    .get("t")
                    .and_then(serde_json::Value::as_str)
                    .ok_or_else(|| D::Error::custom("websocket message is missing tag t"))?;
                match tag {
                    $( $crate::wire_client_msg_tag!($variant) => {
                        let req: $payload = serde_json::from_value(
                            $crate::wire_client_msg_payload!(value $(, $mode)?)
                        )
                        .map_err(D::Error::custom)?;
                        Ok($crate::wire_client_msg_construct!($variant, req $(, { $( $field ),+ })?))
                    }),+
                    other => Err(D::Error::unknown_variant(other, &[])),
                }
            }
        }
    };
}

pub(crate) const TOKEN_HEADER: &str = "x-slop-token";
pub(crate) const SESSION_HEADER: &str = "x-slop-session";
pub(crate) const WS_PATH: &str = "/ws";

pub(crate) mod routes {
    pub(crate) const HEALTH: &str = "/api/health";
    pub(crate) const SESSIONS: &str = "/api/sessions";
    pub(crate) const SESSION: &str = "/api/sessions/:name";
    pub(crate) const SESSION_UPDATE: &str = "/api/sessions/:name";
    pub(crate) const SESSION_CWD: &str = "/api/sessions/:name/cwd";
    pub(crate) const SESSION_SANDBOX: &str = "/api/sessions/:name/sandbox";
    pub(crate) const SESSION_START: &str = "/api/sessions/:name/start";
    pub(crate) const SESSION_STOP: &str = "/api/sessions/:name/stop";
    pub(crate) const SESSION_RESTART: &str = "/api/sessions/:name/restart";
    pub(crate) const SESSION_LABEL: &str = "/api/sessions/:name/label";
    pub(crate) const SESSION_STATE_RESET: &str = "/api/sessions/:name/state/reset";
    pub(crate) const TASKS: &str = "/api/tasks";
    pub(crate) const TASKS_CANCEL: &str = "/api/tasks/cancel";
    pub(crate) const TASKS_REMOVE: &str = "/api/tasks/remove";
    pub(crate) const TASK: &str = "/api/tasks/:id";
    pub(crate) const CAPABILITIES: &str = "/api/capabilities";
    pub(crate) const PROJECTS: &str = "/api/projects";
    pub(crate) const PROJECT: &str = "/api/projects/:name";
    pub(crate) const LIBRARY: &str = "/api/library";
    pub(crate) const LIBRARY_ITEM: &str = "/api/library/:name";
    pub(crate) const LIBRARY_ITEM_RUN: &str = "/api/library/:name/run";
    pub(crate) const RUN: &str = "/api/run";
    pub(crate) const WORKERS: &str = "/api/workers";
    pub(crate) const FILE_ACTION: &str = "/api/file-action";
    pub(crate) const OPEN_APPS: &str = "/api/open-apps";
    pub(crate) const GRANTS: &str = "/api/grants";
    pub(crate) const GRANTOR: &str = "/api/grants/:grantor";
    pub(crate) const STATE: &str = "/api/state";
    pub(crate) const STATE_TRASH: &str = "/api/state/trash";
    pub(crate) const STATE_ITEM: &str = "/api/state/:kind/:key";
    pub(crate) const STATE_TRASH_RESTORE: &str = "/api/state/trash/:key/restore";
    pub(crate) const PRESETS: &str = "/api/presets";
    pub(crate) const PRESET: &str = "/api/presets/:kind/:name";
    pub(crate) const PRESET_COPY: &str = "/api/presets/:kind/:name/copy";
    pub(crate) const CONFIG: &str = "/api/config";
    pub(crate) const CONFIG_PATCH: &str = "/api/config/patch";
    pub(crate) const INSTRUCTIONS_PREVIEW: &str = "/api/instructions/preview";
    pub(crate) const CLIPBOARD: &str = "/api/clipboard";
    pub(crate) const CLIPBOARD_TEXT: &str = "/api/clipboard/text";
    pub(crate) const CLIPBOARD_PRIMARY: &str = "/api/clipboard/primary";
    pub(crate) const CLIPBOARD_PRIMARY_TEXT: &str = "/api/clipboard/primary/text";
    pub(crate) const USAGE: &str = "/api/usage";
    pub(crate) const AUDIO: &str = "/api/audio";
    pub(crate) const JUKEBOX: &str = "/api/jukebox";
    pub(crate) const BROWSE: &str = "/api/browse";
    pub(crate) const READ: &str = "/api/read";
    pub(crate) const HIGHLIGHT: &str = "/api/highlight";
    pub(crate) const IMAGE: &str = "/api/image";
    pub(crate) const FILES: &str = "/api/files";
    pub(crate) const SEARCH: &str = "/api/search";
    pub(crate) const GIT: &str = "/api/git";
}

pub(crate) mod events {
    pub(crate) const CAPABILITIES: &str = "capabilities";
    pub(crate) const SESSIONS: &str = "sessions";
    pub(crate) const PROJECTS: &str = "projects";
    pub(crate) const LIBRARY: &str = "library";
    pub(crate) const SCREEN: &str = "screen";
    pub(crate) const USAGE: &str = "usage";
    pub(crate) const AUDIO: &str = "audio";
    pub(crate) const JUKEBOX: &str = "jukebox";
}

pub(crate) mod messages {
    pub(crate) const REDRAW: &str = "redraw";
    pub(crate) const SUB: &str = "sub";
    pub(crate) const UNSUB: &str = "unsub";
    pub(crate) const KEYS: &str = "keys";
    pub(crate) const RESIZE: &str = "resize";
    pub(crate) const SCROLL: &str = "scroll";
    pub(crate) const MOUSE: &str = "mouse";
    pub(crate) const PASTE: &str = "paste";
    pub(crate) const BREADCRUMB: &str = "breadcrumb";
    pub(crate) const AUDIO: &str = "audio";
}

pub(crate) mod enums {
    pub(crate) mod agent_state {
        pub(crate) const DOWN: &str = "down";
        pub(crate) const WORKING: &str = "working";
        pub(crate) const WAITING: &str = "waiting";
        pub(crate) const IDLE: &str = "idle";
    }
    pub(crate) mod network_mode {
        pub(crate) const NONE: &str = "none";
        pub(crate) const PRIVATE: &str = "private";
        pub(crate) const HOST: &str = "host";
    }
    pub(crate) mod mount_mode {
        pub(crate) const RO: &str = "ro";
        pub(crate) const RW: &str = "rw";
    }
    pub(crate) mod dns_mode {
        pub(crate) const RESOLVED: &str = "resolved";
        pub(crate) const SERVERS: &str = "servers";
    }
    pub(crate) mod library_kind {
        pub(crate) const PROMPT: &str = "prompt";
        pub(crate) const SHELL: &str = "shell";
        pub(crate) const BREADCRUMB: &str = "breadcrumb";
        pub(crate) const FA: &str = "fa";
    }
    pub(crate) mod library_link {
        pub(crate) const PROJECT: &str = "project";
        pub(crate) const TEMP: &str = "temp";
        pub(crate) const ASK: &str = "ask";
    }
    pub(crate) mod file_action_mode {
        pub(crate) const ASK: &str = "ask";
        pub(crate) const SHOW_RESULT: &str = "show_result";
        pub(crate) const OPEN_TERMINAL: &str = "open_terminal";
        pub(crate) const NOTHING: &str = "nothing";
    }
    pub(crate) mod task_status {
        pub(crate) const QUEUED: &str = "queued";
        pub(crate) const ACCEPTED: &str = "accepted";
        pub(crate) const WORKING: &str = "working";
        pub(crate) const DONE: &str = "done";
        pub(crate) const FAILED: &str = "failed";
        pub(crate) const CANCELED: &str = "canceled";
    }
    pub(crate) mod usage_unit {
        pub(crate) const PCT: &str = "pct";
        pub(crate) const USD: &str = "usd";
    }
}

pub(crate) mod usage {
    pub(crate) const CLAUDE_SESSION: &str = "claude_session";
    pub(crate) const CLAUDE_WEEK: &str = "claude_week";
    pub(crate) const CLAUDE_SPEND: &str = "claude_spend";
    pub(crate) const OPENAI_SESSION: &str = "openai_session";
    pub(crate) const OPENAI_WEEK: &str = "openai_week";
    pub(crate) const OPENROUTER_BALANCE: &str = "openrouter_balance";
}

pub(crate) const HOST_IDENTITY: &str = "host";
pub(crate) const ENDPOINT_HOST: &str = "127.0.0.1";
pub(crate) const ENDPOINT_PORT: u16 = 7717;
pub(crate) const TEMP_ROOT: &str = "/tmp/slopworld";
pub(crate) const SCROLLBACK_LINES: u32 = 10000;
pub(crate) const TERMINAL_MIN_COLS: u16 = 20;
pub(crate) const TERMINAL_MAX_COLS: u16 = 500;
pub(crate) const TERMINAL_MIN_ROWS: u16 = 5;
pub(crate) const TERMINAL_MAX_ROWS: u16 = 200;
pub(crate) const USAGE_POLL_SECS: u64 = 60;
pub(crate) const DEFAULT_CLAUDE_CREDENTIALS: &str = "~/.claude/.credentials.json";
pub(crate) const DEFAULT_OPENAI_CREDENTIALS: &str = "~/.codex/auth.json";
pub(crate) const DEFAULT_TITLE_MODEL: &str = "google/gemini-3.1-flash-lite";
pub(crate) const DEFAULT_TITLE_MIN_CHARS: u64 = 20;
pub(crate) const DEFAULT_AGENT: &str = "claude";
pub(crate) const DEFAULT_AGENT_SHELL: &str = "bash";
pub(crate) const DEFAULT_SHELL: &str = "bash";
pub(crate) const DEFAULT_PAGER: &str = "less";
pub(crate) const DEFAULT_EDITOR: &str = "micro";
pub(crate) const DEFAULT_HIGHLIGHTER: &str = "highlight --out-format=xterm256";
pub(crate) const DEFAULT_INSTRUCTIONS_MOUNT_PATH: &str = "SLOPWORLD.md";
pub(crate) const DEFAULT_SUMMARY_PROMPT: &str = "Summarise this coding request in at most 6 words for a session title. Reply with only the title, without quotes, punctuation, or commentary.";
pub(crate) const DEFAULT_INSTRUCTIONS_BREADCRUMB: &str = "Read `{{ mount_path }}` for SlopWorld runtime context. It is a generated snapshot, not project instructions. When delegating, send work once and use `slopctl wait ID` for the result; do not poll `task`, `inbox`, or `status`.";
pub(crate) const DEFAULT_WORKER_PROMPT: &str = "You are a SlopWorld worker. Your assigned task ID is $SLOPWORLD_TASK_ID. Run `slopctl task \"$SLOPWORLD_TASK_ID\"` once, then `slopctl accept \"$SLOPWORLD_TASK_ID\"`. Use `slopctl progress \"$SLOPWORLD_TASK_ID\" \"note\"` while working and conclude with `slopctl finish \"$SLOPWORLD_TASK_ID\" \"result\"` or `slopctl fail \"$SLOPWORLD_TASK_ID\" \"reason\"`. Do not search the inbox or poll task status.\n\nWorker task: use `$SLOPWORLD_TASK_ID` with `slopctl task`, then `accept`, `progress`, and finally `finish` or `fail`. Do not search the inbox or poll task status.";
pub(crate) const DEFAULT_INSTRUCTIONS_BREADCRUMB_ENABLED: bool = true;
pub(crate) const DEFAULT_BIND: &str = "127.0.0.1:7717";
