#!/usr/bin/env python3
"""Generate the Rust license inventory from Cargo's locked dependency graph."""

import json
import subprocess

from tools import ROOT


def cell(value):
    return value.replace('|', '\\|').replace('\n', ' ')


def main():
    metadata = json.loads(
        subprocess.check_output(
            [
                'cargo',
                'metadata',
                '--locked',
                '--format-version',
                '1',
                '--manifest-path',
                str(ROOT / 'slopd/Cargo.toml'),
            ],
            text=True,
            cwd=ROOT,
        )
    )
    nodes = {node['id']: node for node in metadata['resolve']['nodes']}
    pending = list(metadata['workspace_members'])
    reached = set()
    while pending:
        package_id = pending.pop()
        if package_id in reached:
            continue
        reached.add(package_id)
        pending.extend(nodes[package_id]['dependencies'])
    members = set(metadata['workspace_members'])
    packages = sorted(
        (package for package in metadata['packages'] if package['id'] in reached - members),
        key=lambda package: (package['name'], package['version'], package['id']),
    )
    lines = [
        '# Rust dependency licenses',
        '',
        'Generated by `just rust-licenses` from `cargo metadata --locked` for',
        '`slopd/Cargo.toml`. Includes direct and transitive runtime, build, and',
        "development dependencies across all target platforms, with the manifest's",
        'default feature selection. Workspace packages are excluded.',
        '',
        'License expressions are copied from crate metadata without choosing between',
        'alternatives. This inventory does not contain full license texts or notices',
        'and does not identify which crates are included in a particular binary.',
        '',
        '| Crate | Version | License |',
        '| --- | --- | --- |',
    ]
    for package in packages:
        license_name = package['license']
        if not license_name:
            license_name = (
                'Custom (license-file: ' + package['license_file'] + ')' if package['license_file'] else 'Not specified'
            )
        lines.append(
            '| '
            + ' | '.join(
                cell(value)
                for value in (
                    package['name'],
                    package['version'],
                    license_name,
                )
            )
            + ' |'
        )
    destination = ROOT / 'licenses/rust-dependencies.md'
    destination.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Wrote {len(packages)} crates to {destination.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
