"""Stage full MIT notices from the sidecar's locked Cargo dependency graph."""

import json
import subprocess
from pathlib import Path

from tools import ROOT
from tools.utils import command
from tools.utils import run_main


def main() -> None:
    dependencies: dict[str, dict[str, str]] = {}
    for target in (
        'x86_64-unknown-linux-gnu',
        'aarch64-unknown-linux-gnu',
        'x86_64-apple-darwin',
        'aarch64-apple-darwin',
    ):
        metadata = json.loads(
            subprocess.check_output(
                [
                    *command('CARGO', 'cargo'),
                    'metadata',
                    '--locked',
                    '--format-version',
                    '1',
                    '--filter-platform',
                    target,
                    '--manifest-path',
                    str(ROOT / 'slopcar/Cargo.toml'),
                ],
                text=True,
                cwd=ROOT,
            )
        )
        nodes = {node['id']: node for node in metadata['resolve']['nodes']}
        reached = set()
        pending = list(metadata['workspace_members'])
        while pending:
            package_id = pending.pop()
            if package_id not in reached:
                reached.add(package_id)
                pending.extend(nodes[package_id]['dependencies'])
        members = set(metadata['workspace_members'])
        dependencies.update(
            (package['id'], package) for package in metadata['packages'] if package['id'] in reached - members
        )
    packages = sorted(dependencies.values(), key=lambda package: (package['name'], package['version']))
    sections = [
        'Slopcar third-party notices',
        'Generated by just refresh-sidecar-licenses from slopcar/Cargo.lock.\n'
        'Includes Linux and macOS on x86_64/arm64, including development dependencies.',
    ]
    for package in packages:
        # Each current dependency offers MIT. Fail rather than silently omit a notice
        # if a future lock update introduces a different license or layout.
        if 'MIT' not in package['license'].split(' OR '):
            raise ValueError(f'Review license for {package["name"]}: {package["license"]}')
        source = Path(package['manifest_path']).parent
        candidates = [source / name for name in ('LICENSE-MIT', 'LICENSE-MIT.txt', 'LICENSE-MIT.md')]
        candidates.extend(source.glob('LICENSE*'))
        notice = next(
            (
                path
                for path in candidates
                if path.is_file() and 'Permission is hereby granted' in path.read_text(encoding='utf-8')
            ),
            None,
        )
        if notice is None:
            raise ValueError(f'Missing full MIT notice for {package["name"]}')
        sections.append(f'{package["name"]} {package["version"]} — MIT\n\n{notice.read_text(encoding="utf-8").strip()}')
    destination = ROOT / 'licenses/slopcar/THIRD-PARTY-NOTICES.txt'
    destination.parent.mkdir(parents=True, exist_ok=True)
    content = '\n\n'.join(sections) + '\n'
    if not destination.exists() or destination.read_text(encoding='utf-8') != content:
        destination.write_text(content, encoding='utf-8')
    print(f'Wrote {len(packages)} dependency notices to {destination.relative_to(ROOT)}')


if __name__ == '__main__':
    run_main(main)
