using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SlopWorld
{
    // The daemon owns the file and hands these over parsed, so nothing in the mod has
    // to speak TOML. This is a read model for the settings pages, not a second schema for
    // the whole daemon config. Writes are partial patches, so fields not represented here
    // remain untouched on the server.
    public class DaemonConfig
    {
        public const string DefaultInstructionsTemplate =
            "# SlopWorld agent context\n\n" +
            "Read the project's `README.md` and any applicable `AGENTS.md` files for project " +
            "instructions. This generated `{{ file }}` is mounted at `{{ mount_path }}` and is " +
            "runtime context, not a replacement for them.\n\n" +
            "{{ runtime_context }}\n";
        public const string DefaultInstructionsBreadcrumb =
            "Read `{{ mount_path }}` for SlopWorld runtime context. It is a generated snapshot, " +
            "not project instructions.";
        public const string DefaultWorkerPrompt =
            "You are a SlopWorld worker. Your assigned task is $SLOPWORLD_TASK_ID. " +
            "Run slopctl task with that exact ID, accept it, then complete it. " +
            "Do not duplicate the task body into the prompt and do not rely on an ambiguous " +
            "inbox search.";

        public int UsagePollSecs = 60;
        // One entry per usage window. A zero interval means the global interval applies.
        public Dictionary<string, UsageItemConfig> UsageItems =
            new Dictionary<string, UsageItemConfig>();
        // Where the daemon looks for Claude Code's OAuth token.
        public string ClaudeCredentials = "~/.claude/.credentials.json";
        // Blank means the daemon reads OPENROUTER_API_KEY out of its own environment.
        public string OpenrouterKeyFile = "";
        // Codex's ChatGPT login carries the token the usage endpoint needs. Unlike a key,
        // it is a live login file that the daemon reads fresh and never sends to the mod.
        public string OpenaiCredentials = "~/.codex/auth.json";
        // Prompt- and command-derived titles use a separate OpenRouter request.
        public string AgentTitles = "never";
        public string TitleModel = "google/gemini-3.1-flash-lite";
        public int TitleMinChars = 20;
        // Pi titles are generated by slopd before input reaches the sandbox.
        public string PiTitles = "always";
        // Host terminal commands are summarized on submission, independently of agent policy.
        public bool HostTitles = true;
        // The generated project-root runtime manifest. The body is a Markdown template, with
        // {{ runtime_context }} expanding to the daemon's live snapshot.
        public string InstructionsTemplate = DefaultInstructionsTemplate;
        public string InstructionsMountPath = "SLOPWORLD.md";
        public string InstructionsBreadcrumb = DefaultInstructionsBreadcrumb;
        public bool InstructionsBreadcrumbEnabled = true;
        public string WorkerPrompt = DefaultWorkerPrompt;

        public string RenderInstructionsBreadcrumb(string project)
        {
            var values = new Dictionary<string, string>
            {
                ["project"] = project ?? "",
                ["mount_path"] = InstructionsMountPath ?? "",
                ["file"] = "SLOPWORLD.md",
            };
            return RenderTemplate(InstructionsBreadcrumb ?? "", values);
        }

        static string RenderTemplate(string template, Dictionary<string, string> values)
        {
            var output = new StringBuilder(template.Length);
            int offset = 0;
            while (offset < template.Length)
            {
                int start = template.IndexOf("{{", offset, System.StringComparison.Ordinal);
                if (start < 0)
                {
                    output.Append(template, offset, template.Length - offset);
                    break;
                }
                output.Append(template, offset, start - offset);
                int end = template.IndexOf("}}", start + 2, System.StringComparison.Ordinal);
                if (end < 0)
                {
                    output.Append(template, start, template.Length - start);
                    break;
                }
                string key = template.Substring(start + 2, end - start - 2).Trim();
                if (values.TryGetValue(key, out string value))
                    output.Append(value);
                else
                    output.Append(template, start, end + 2 - start);
                offset = end + 2;
            }
            return output.ToString();
        }

        // Both name a command preset: what an agent that names none of its own runs, and
        // what a shell errand runs. What each one *is* is a TOML file the daemon reads.
        public string Agent = "claude";
        public string Shell = "bash";
        public string Pager = "less";
        public string Editor = "micro";
        public string Highlighter = "highlight --out-format=xterm256";

        public static DaemonConfig FromJson(JVal v)
        {
            var d = v["daemon"];
            var f = v["defaults"];
            var c = v["commands"];
            var i = d["instructions"];
            return new DaemonConfig
            {
                UsagePollSecs = d["usage_poll_secs"].AsInt(60),
                UsageItems = UsageItemsFromJson(d["usage_items"]),
                ClaudeCredentials =
                    d["claude_credentials"].AsString("~/.claude/.credentials.json"),
                OpenrouterKeyFile = d["openrouter_key_file"].AsString(),
                OpenaiCredentials = d["openai_credentials"].AsString("~/.codex/auth.json"),
                AgentTitles = d["agent_titles"].AsString("never"),
                TitleModel = d["title_model"].AsString("google/gemini-3.1-flash-lite"),
                TitleMinChars = d["title_min_chars"].AsInt(20),
                PiTitles = d["pi_titles"].AsString("always"),
                HostTitles = d["host_titles"].AsBool(true),
                InstructionsTemplate = i["template"].AsString(DefaultInstructionsTemplate),
                InstructionsMountPath = i["mount_path"].AsString("SLOPWORLD.md"),
                InstructionsBreadcrumb =
                    i["breadcrumb"].AsString(DefaultInstructionsBreadcrumb),
                InstructionsBreadcrumbEnabled = i["breadcrumb_enabled"].AsBool(true),
                WorkerPrompt = i["worker_prompt"].AsString(DefaultWorkerPrompt),

                Agent = f["agent"].AsString("claude"),
                Shell = f["shell"].AsString("bash"),
                Pager = c["pager"].AsString("less"),
                Editor = c["editor"].AsString("micro"),
                Highlighter = c["highlighter"].AsString("highlight --out-format=xterm256"),
            };
        }

        public class UsageItemConfig
        {
            public bool Poll = true;
            // Zero is the client-side representation of an omitted TOML interval.
            public int IntervalSecs;
        }

        static Dictionary<string, UsageItemConfig> UsageItemsFromJson(JVal value)
        {
            var items = new Dictionary<string, UsageItemConfig>();
            if (value.Obj == null) return items;

            foreach (var pair in value.Obj)
                items[pair.Key] = new UsageItemConfig
                {
                    Poll = pair.Value["poll"].AsBool(true),
                    IntervalSecs = pair.Value["interval_secs"].AsInt(0),
                };
            return items;
        }

        // This deliberately omits bind, token, projects, sessions, state rules and sandbox
        // presets. The daemon deep-merges this object before validating it.
        public string ToPatchJson() =>
            "{\"daemon\":{" +
            $"\"usage_poll_secs\":{UsagePollSecs}," +
            $"\"usage_items\":{UsageItemsJson()}," +
            $"\"claude_credentials\":{JVal.Q(ClaudeCredentials)}," +
            $"\"openrouter_key_file\":{JVal.Q(OpenrouterKeyFile)}," +
            $"\"openai_credentials\":{JVal.Q(OpenaiCredentials)}," +
            $"\"agent_titles\":{JVal.Q(AgentTitles)}," +
            $"\"title_model\":{JVal.Q(TitleModel)}," +
            $"\"title_min_chars\":{TitleMinChars}," +
            $"\"pi_titles\":{JVal.Q(PiTitles)}," +
            $"\"host_titles\":{JVal.B(HostTitles)}," +
            "\"instructions\":{" +
            $"\"template\":{JVal.Q(InstructionsTemplate)}," +
                $"\"mount_path\":{JVal.Q(InstructionsMountPath)}," +
                $"\"breadcrumb\":{JVal.Q(InstructionsBreadcrumb)}," +
                $"\"breadcrumb_enabled\":{JVal.B(InstructionsBreadcrumbEnabled)}," +
                $"\"worker_prompt\":{JVal.Q(WorkerPrompt)}" +
            "}" +
            "}," +
            "\"defaults\":{" +
            $"\"agent\":{JVal.Q(Agent)},\"shell\":{JVal.Q(Shell)}" +
            "}," +
            "\"commands\":{" +
            $"\"pager\":{JVal.Q(Pager)},\"editor\":{JVal.Q(Editor)}," +
            $"\"highlighter\":{JVal.Q(Highlighter)}" +
            "}}";

        string UsageItemsJson()
        {
            var parts = new List<string>();
            foreach (var pair in UsageItems)
            {
                var item = pair.Value ?? new UsageItemConfig();
                // Zero is explicit here so a previously saved per-item override can be
                // cleared through the daemon's deep-merge patch.
                string interval = item.IntervalSecs > 0
                    ? item.IntervalSecs.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : "0";
                parts.Add(JVal.Q(pair.Key) + ":{\"poll\":" + JVal.B(item.Poll) +
                    ",\"interval_secs\":" + interval + "}");
            }
            return "{" + string.Join(",", parts.ToArray()) + "}";
        }

        // One entry per line, which is how the GUI edits these lists.
        public static string Lines(List<string> items) =>
            string.Join("\n", items.ToArray());

        public static List<string> Split(string text) =>
            (text ?? "").Split('\n')
                .Select(l => l.Trim())
                .Where(l => l.Length > 0)
                .ToList();
    }
}
