using System.Collections.Generic;
using System.Linq;

namespace SlopWorld
{
    // The daemon owns the file and hands these over parsed, so nothing in the mod has
    // to speak TOML. This is a read model for the settings pages, not a second schema for
    // the whole daemon config. Writes are partial patches, so fields not represented here
    // remain untouched on the server.
    public class SlopConfig
    {
        public int UsagePollSecs = 60;
        // One entry per usage window. A zero interval means the global interval applies.
        public Dictionary<string, UsageItemConfig> UsageItems =
            new Dictionary<string, UsageItemConfig>();
        // Where the daemon looks for Claude Code's OAuth token.
        public string ClaudeCredentials = "~/.claude/.credentials.json";
        // Blank means the daemon reads OPENROUTER_API_KEY out of its own environment.
        public string OpenrouterKeyFile = "";
        // Codex's ChatGPT login carries the token the usage endpoint needs. Unlike a key,
        // it is a live login file that the daemon reads fresh and never sends to the mod.
        public string OpenaiCredentials = "~/.codex/auth.json";
        // Prompt- and command-derived titles use a separate OpenRouter request.
        public string AgentTitles = "never";
        public string TitleModel = "google/gemini-3.1-flash-lite";
        public int TitleMinChars = 20;
        // Pi titles are generated by slopd before input reaches the sandbox.
        public string PiTitles = "always";
        // Host terminal commands are summarized on submission, independently of agent policy.
        public bool HostTitles = true;
        // The generated project-root runtime manifest. The body is a Markdown template, with
        // {{ runtime_context }} expanding to the daemon's live snapshot.
        public string InstructionsTemplate = "{{ runtime_context }}";
        public string InstructionsMountPath = "SLOPWORLD.md";
        public bool InstructionsBreadcrumbEnabled = true;

        // Both name a command preset: what an agent that names none of its own runs, and
        // what a shell errand runs. What each one *is* is a TOML file the daemon reads.
        public string Agent = "claude";
        public string Shell = "bash";
        public string Pager = "less";
        public string Editor = "micro";
        public string Highlighter = "highlight --out-format=xterm256";

        public static SlopConfig FromJson(JVal v)
        {
            var d = v["daemon"];
            var f = v["defaults"];
            var c = v["commands"];
            var i = d["instructions"];
            return new SlopConfig
            {
                UsagePollSecs = d["usage_poll_secs"].AsInt(60),
                UsageItems = UsageItemsFromJson(d["usage_items"]),
                ClaudeCredentials =
                    d["claude_credentials"].AsString("~/.claude/.credentials.json"),
                OpenrouterKeyFile = d["openrouter_key_file"].AsString(),
                OpenaiCredentials = d["openai_credentials"].AsString("~/.codex/auth.json"),
                AgentTitles = d["agent_titles"].AsString("never"),
                TitleModel = d["title_model"].AsString("google/gemini-3.1-flash-lite"),
                TitleMinChars = d["title_min_chars"].AsInt(20),
                PiTitles = d["pi_titles"].AsString("always"),
                HostTitles = d["host_titles"].AsBool(true),
                InstructionsTemplate = i["template"].AsString("{{ runtime_context }}"),
                InstructionsMountPath = i["mount_path"].AsString("SLOPWORLD.md"),
                InstructionsBreadcrumbEnabled = i["breadcrumb_enabled"].AsBool(true),

                Agent = f["agent"].AsString("claude"),
                Shell = f["shell"].AsString("bash"),
                Pager = c["pager"].AsString("less"),
                Editor = c["editor"].AsString("micro"),
                Highlighter = c["highlighter"].AsString("highlight --out-format=xterm256"),
            };
        }

        public class UsageItemConfig
        {
            public bool Poll = true;
            // Zero is the client-side representation of an omitted TOML interval.
            public int IntervalSecs;
        }

        static Dictionary<string, UsageItemConfig> UsageItemsFromJson(JVal value)
        {
            var items = new Dictionary<string, UsageItemConfig>();
            if (value.Obj == null) return items;

            foreach (var pair in value.Obj)
                items[pair.Key] = new UsageItemConfig
                {
                    Poll = pair.Value["poll"].AsBool(true),
                    IntervalSecs = pair.Value["interval_secs"].AsInt(0),
                };
            return items;
        }

        // This deliberately omits bind, token, projects, sessions, state rules and sandbox
        // presets. The daemon deep-merges this object before validating it.
        public string ToPatchJson() =>
            "{\"daemon\":{" +
            $"\"usage_poll_secs\":{UsagePollSecs}," +
            $"\"usage_items\":{UsageItemsJson()}," +
            $"\"claude_credentials\":{JVal.Q(ClaudeCredentials)}," +
            $"\"openrouter_key_file\":{JVal.Q(OpenrouterKeyFile)}," +
            $"\"openai_credentials\":{JVal.Q(OpenaiCredentials)}," +
            $"\"agent_titles\":{JVal.Q(AgentTitles)}," +
            $"\"title_model\":{JVal.Q(TitleModel)}," +
            $"\"title_min_chars\":{TitleMinChars}," +
            $"\"pi_titles\":{JVal.Q(PiTitles)}," +
            $"\"host_titles\":{JVal.B(HostTitles)}," +
            "\"instructions\":{" +
            $"\"template\":{JVal.Q(InstructionsTemplate)}," +
            $"\"mount_path\":{JVal.Q(InstructionsMountPath)}," +
            $"\"breadcrumb_enabled\":{JVal.B(InstructionsBreadcrumbEnabled)}" +
            "}" +
            "}," +
            "\"defaults\":{" +
            $"\"agent\":{JVal.Q(Agent)},\"shell\":{JVal.Q(Shell)}" +
            "}," +
            "\"commands\":{" +
            $"\"pager\":{JVal.Q(Pager)},\"editor\":{JVal.Q(Editor)}," +
            $"\"highlighter\":{JVal.Q(Highlighter)}" +
            "}}";

        string UsageItemsJson()
        {
            var parts = new List<string>();
            foreach (var pair in UsageItems)
            {
                var item = pair.Value ?? new UsageItemConfig();
                // Zero is explicit here so a previously saved per-item override can be
                // cleared through the daemon's deep-merge patch.
                string interval = item.IntervalSecs > 0
                    ? item.IntervalSecs.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : "0";
                parts.Add(JVal.Q(pair.Key) + ":{\"poll\":" + JVal.B(item.Poll) +
                    ",\"interval_secs\":" + interval + "}");
            }
            return "{" + string.Join(",", parts.ToArray()) + "}";
        }

        // One entry per line, which is how the GUI edits these lists.
        public static string Lines(List<string> items) =>
            string.Join("\n", items.ToArray());

        public static List<string> Split(string text) =>
            (text ?? "").Split('\n')
                .Select(l => l.Trim())
                .Where(l => l.Length > 0)
                .ToList();
    }
}
