<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Google.Protobuf" Version="3.36.1" /></ItemGroup>
  <Target Name="CopyRuntime" AfterTargets="Build">
    <Copy SourceFiles="@(ReferenceCopyLocalPaths)" DestinationFolder="../Assemblies" />
  </Target>
</Project>
