# Copied from the locally installed font; no download performed.
# licenses/noto-emoji/LICENSE.txt is copied from /usr/share/licenses/noto-fonts-emoji/LICENSE.
upstream_url = "https://github.com/googlefonts/noto-emoji"
installed_source = "/usr/share/fonts/noto/NotoColorEmoji.ttf"
version = "Version 2.051;GOOG;noto-emoji:20250818:e92753bfa55fd449e427d4d325f9c8c40408c74e"
font_file = "NotoColorEmoji.ttf"
font_sha256 = "72a635cb3d2f3524c51620cdde406b217204e8a6a06c6a096ff8ed4b5fd6e27b"
