// <auto-generated />
// Source: shared/defaults.yaml; regenerate with `make api-contract`.
#![allow(dead_code)]

pub(crate) const ENDPOINT_HOST: &str = "127.0.0.1";
pub(crate) const ENDPOINT_PORT: u16 = 7717;
pub(crate) const TEMP_ROOT: &str = "/tmp/slopworld";
pub(crate) const SCROLLBACK_LINES: u32 = 10000;
pub(crate) const USAGE_POLL_SECS: u64 = 60;
pub(crate) const DEFAULT_CLAUDE_CREDENTIALS: &str = "~/.claude/.credentials.json";
pub(crate) const DEFAULT_OPENAI_CREDENTIALS: &str = "~/.codex/auth.json";
pub(crate) const DEFAULT_TITLE_MODEL: &str = "google/gemini-3.1-flash-lite";
pub(crate) const DEFAULT_TITLE_MIN_CHARS: u64 = 20;
pub(crate) const DEFAULT_AGENT: &str = "claude";
pub(crate) const DEFAULT_AGENT_SHELL: &str = "bash";
pub(crate) const DEFAULT_SHELL: &str = "bash";
pub(crate) const DEFAULT_PAGER: &str = "less";
pub(crate) const DEFAULT_EDITOR: &str = "micro";
pub(crate) const DEFAULT_HIGHLIGHTER: &str = "highlight --out-format=xterm256";
pub(crate) const DEFAULT_INSTRUCTIONS_MOUNT_PATH: &str = "SLOPWORLD.md";
pub(crate) const DEFAULT_SUMMARY_PROMPT: &str = "Summarise this coding request in at most 6 words for a session title. Reply with only the title, without quotes, punctuation, or commentary.";
pub(crate) const DEFAULT_INSTRUCTIONS_BREADCRUMB: &str = "Read `{{ mount_path }}` for SlopWorld runtime context. It is a generated snapshot, not project instructions. When delegating, send work once and use `slopctl wait ID` for the result; do not poll `task`, `inbox`, or `status`.";
pub(crate) const DEFAULT_WORKER_PROMPT: &str = "You are a SlopWorld worker. Your assigned task ID is $SLOPWORLD_TASK_ID. Run `slopctl task \"$SLOPWORLD_TASK_ID\"` once, then `slopctl accept \"$SLOPWORLD_TASK_ID\"`. Use `slopctl progress \"$SLOPWORLD_TASK_ID\" \"note\"` while working and conclude with `slopctl finish \"$SLOPWORLD_TASK_ID\" \"result\"` or `slopctl fail \"$SLOPWORLD_TASK_ID\" \"reason\"`. Do not search the inbox or poll task status.\n\nWorker task: use `$SLOPWORLD_TASK_ID` with `slopctl task`, then `accept`, `progress`, and finally `finish` or `fail`. Do not search the inbox or poll task status.";
pub(crate) const DEFAULT_INSTRUCTIONS_BREADCRUMB_ENABLED: bool = true;
pub(crate) const DEFAULT_BIND: &str = "127.0.0.1:7717";
