// Generated by tools/protocol/protobuf_http.py. Do not edit.
#![allow(
    dead_code,
    reason = "generated route adapters are shared across daemon and mod clients"
)]
use super::wire;
use prost::Message;
use serde_json::Value;
fn encode_wire<T>(value: Value) -> anyhow::Result<Vec<u8>>
where
    T: serde::de::DeserializeOwned + Message,
{
    Ok(serde_json::from_value::<T>(value)?.encode_to_vec())
}
pub(crate) const CONTENT_TYPE: &str = "application/x-protobuf";
fn matches(pattern: &str, path: &str) -> bool {
    let path = path.split('?').next().unwrap_or(path);
    let a: Vec<_> = pattern.split('/').collect();
    let b: Vec<_> = path.split('/').collect();
    a.len() == b.len() && a.iter().zip(b).all(|(a, b)| a.starts_with(':') || *a == b)
}
#[derive(Clone, Copy)]
enum RequestKind {
    AgentTemplate,
    ClipReq,
    ConfigPatch,
    CopyPresetReq,
    CreateAgentTemplateReq,
    CreateTaskReq,
    CreateWorktreeReq,
    Empty,
    FileActionReq,
    FileReq,
    GrantReq,
    HighlightReq,
    LabelReq,
    LibraryItem,
    PresetRequest,
    Project,
    ProjectPreviewReq,
    ReaderPinnedReq,
    RedrawReq,
    RemoveTasksReq,
    ReplaceConfigRequest,
    RunReq,
    RunWhere,
    SaveTemplateRequest,
    SessionConfig,
    SettingsPreviewRequest,
    SpawnWorkerReq,
    Station,
    UpdateTaskReq,
}
#[derive(Clone, Copy)]
enum ResponseKind {
    Ack,
    AppsReply,
    AudioState,
    BrowseResult,
    Capabilities,
    ConfigResult,
    FileStatResult,
    GitResult,
    GrantResult,
    GrantsReply,
    Health,
    HighlightThemes,
    ImageResult,
    JukeboxCatalog,
    LibraryReply,
    OutputResult,
    PathResult,
    PresetsReply,
    Project,
    ProjectPreviewResult,
    ProjectsReply,
    SandboxReport,
    SearchResult,
    SessionResult,
    SessionView,
    SessionsReply,
    SettingsPreview,
    StoredStates,
    TaskBatchResult,
    TaskResult,
    TasksReply,
    TemplateResult,
    TemplatesReply,
    TextResult,
    UsageSnapshot,
    WhereIsReply,
    WorkerResult,
    Worktree,
    WorktreeBase,
    WorktreesReply,
}
use RequestKind as Req;
use ResponseKind as Resp;
type Route = (&'static str, RequestKind, ResponseKind);
const ROUTES: &[Route] = &[
    ("GET /api/health", Req::Empty, Resp::Health),
    ("GET /api/sessions", Req::Empty, Resp::SessionsReply),
    ("POST /api/sessions", Req::SessionConfig, Resp::Ack),
    (
        "POST /api/settings/preview",
        Req::SettingsPreviewRequest,
        Resp::SettingsPreview,
    ),
    ("GET /api/templates", Req::Empty, Resp::TemplatesReply),
    (
        "POST /api/templates",
        Req::SaveTemplateRequest,
        Resp::TemplateResult,
    ),
    (
        "GET /api/templates/spawnable",
        Req::Empty,
        Resp::TemplatesReply,
    ),
    ("GET /api/tasks", Req::Empty, Resp::TasksReply),
    ("POST /api/tasks", Req::CreateTaskReq, Resp::TaskResult),
    ("DELETE /api/tasks", Req::Empty, Resp::TaskBatchResult),
    (
        "POST /api/tasks/cancel",
        Req::RemoveTasksReq,
        Resp::TaskBatchResult,
    ),
    (
        "POST /api/tasks/remove",
        Req::RemoveTasksReq,
        Resp::TaskBatchResult,
    ),
    ("GET /api/capabilities", Req::Empty, Resp::Capabilities),
    ("GET /api/whereis", Req::Empty, Resp::WhereIsReply),
    ("GET /api/projects", Req::Empty, Resp::ProjectsReply),
    ("POST /api/projects", Req::Project, Resp::Ack),
    (
        "POST /api/projects/preview",
        Req::ProjectPreviewReq,
        Resp::ProjectPreviewResult,
    ),
    ("GET /api/library", Req::Empty, Resp::LibraryReply),
    ("POST /api/library", Req::LibraryItem, Resp::Ack),
    ("POST /api/run", Req::RunReq, Resp::SessionResult),
    ("GET /api/worktrees", Req::Empty, Resp::WorktreesReply),
    (
        "POST /api/worktrees",
        Req::CreateWorktreeReq,
        Resp::Worktree,
    ),
    (
        "POST /api/worktrees/preview",
        Req::CreateWorktreeReq,
        Resp::WorktreeBase,
    ),
    ("POST /api/workers", Req::SpawnWorkerReq, Resp::WorkerResult),
    (
        "POST /api/file-action",
        Req::FileActionReq,
        Resp::OutputResult,
    ),
    ("GET /api/open-apps", Req::Empty, Resp::AppsReply),
    ("GET /api/grants", Req::Empty, Resp::GrantsReply),
    ("POST /api/grants", Req::GrantReq, Resp::GrantResult),
    ("GET /api/state", Req::Empty, Resp::StoredStates),
    ("DELETE /api/state/trash", Req::Empty, Resp::Ack),
    ("GET /api/presets", Req::Empty, Resp::PresetsReply),
    ("GET /api/config", Req::Empty, Resp::ConfigResult),
    ("PUT /api/config", Req::ReplaceConfigRequest, Resp::Ack),
    ("PUT /api/config/patch", Req::ConfigPatch, Resp::Ack),
    ("GET /api/clipboard", Req::Empty, Resp::TextResult),
    ("POST /api/clipboard", Req::ClipReq, Resp::Ack),
    ("GET /api/clipboard/text", Req::Empty, Resp::TextResult),
    ("GET /api/clipboard/primary", Req::Empty, Resp::TextResult),
    ("POST /api/clipboard/primary", Req::ClipReq, Resp::Ack),
    (
        "GET /api/clipboard/primary/text",
        Req::Empty,
        Resp::TextResult,
    ),
    ("GET /api/usage", Req::Empty, Resp::UsageSnapshot),
    ("GET /api/audio", Req::Empty, Resp::AudioState),
    ("POST /api/ncspot", Req::RedrawReq, Resp::SessionResult),
    ("GET /api/jukebox", Req::Empty, Resp::JukeboxCatalog),
    ("GET /api/jukebox/presets", Req::Empty, Resp::JukeboxCatalog),
    ("POST /api/jukebox/presets", Req::Station, Resp::Ack),
    ("GET /api/browse", Req::Empty, Resp::BrowseResult),
    ("GET /api/files/stat", Req::Empty, Resp::FileStatResult),
    ("GET /api/read", Req::Empty, Resp::TextResult),
    ("POST /api/highlight", Req::HighlightReq, Resp::TextResult),
    (
        "GET /api/highlight/themes",
        Req::Empty,
        Resp::HighlightThemes,
    ),
    ("GET /api/image", Req::Empty, Resp::ImageResult),
    ("POST /api/files", Req::FileReq, Resp::Ack),
    ("PUT /api/files", Req::FileReq, Resp::Ack),
    ("DELETE /api/files", Req::FileReq, Resp::Ack),
    ("GET /api/search", Req::Empty, Resp::SearchResult),
    ("GET /api/git", Req::Empty, Resp::GitResult),
    ("GET /api/sessions/:name", Req::Empty, Resp::SessionView),
    ("DELETE /api/sessions/:name", Req::Empty, Resp::Ack),
    ("PUT /api/sessions/:name", Req::SessionConfig, Resp::Ack),
    ("GET /api/sessions/:name/cwd", Req::Empty, Resp::PathResult),
    (
        "GET /api/sessions/:name/sandbox",
        Req::Empty,
        Resp::SandboxReport,
    ),
    ("POST /api/sessions/:name/start", Req::Empty, Resp::Ack),
    ("POST /api/sessions/:name/stop", Req::Empty, Resp::Ack),
    ("POST /api/sessions/:name/restart", Req::Empty, Resp::Ack),
    ("PUT /api/sessions/:name/label", Req::LabelReq, Resp::Ack),
    (
        "PUT /api/sessions/:name/reader-pinned",
        Req::ReaderPinnedReq,
        Resp::Ack,
    ),
    (
        "POST /api/sessions/:name/state/reset",
        Req::Empty,
        Resp::Ack,
    ),
    (
        "PUT /api/templates/:name",
        Req::AgentTemplate,
        Resp::TemplateResult,
    ),
    ("DELETE /api/templates/:name", Req::Empty, Resp::Ack),
    (
        "POST /api/templates/:name/create",
        Req::CreateAgentTemplateReq,
        Resp::SessionResult,
    ),
    ("GET /api/tasks/:id", Req::Empty, Resp::TaskResult),
    ("POST /api/tasks/:id", Req::UpdateTaskReq, Resp::TaskResult),
    ("DELETE /api/tasks/:id", Req::Empty, Resp::TaskResult),
    ("GET /api/projects/:name", Req::Empty, Resp::Project),
    ("PUT /api/projects/:name", Req::Project, Resp::Ack),
    ("DELETE /api/projects/:name", Req::Empty, Resp::Ack),
    ("PUT /api/library/:name", Req::LibraryItem, Resp::Ack),
    ("DELETE /api/library/:name", Req::Empty, Resp::Ack),
    (
        "POST /api/library/:name/run",
        Req::RunWhere,
        Resp::SessionResult,
    ),
    ("DELETE /api/worktrees/:id", Req::Empty, Resp::Ack),
    (
        "PUT /api/worktrees/:id",
        Req::CreateWorktreeReq,
        Resp::Worktree,
    ),
    ("DELETE /api/grants/:grantor", Req::Empty, Resp::Ack),
    (
        "POST /api/state/trash/:key/restore",
        Req::Empty,
        Resp::SessionResult,
    ),
    ("PUT /api/jukebox/presets/:id", Req::Station, Resp::Ack),
    ("DELETE /api/jukebox/presets/:id", Req::Empty, Resp::Ack),
    ("DELETE /api/state/:kind/:key", Req::Empty, Resp::Ack),
    (
        "PUT /api/presets/:kind/:name",
        Req::PresetRequest,
        Resp::Ack,
    ),
    ("DELETE /api/presets/:kind/:name", Req::Empty, Resp::Ack),
    (
        "POST /api/presets/:kind/:name/copy",
        Req::CopyPresetReq,
        Resp::Ack,
    ),
];
fn route(method: &str, path: &str) -> anyhow::Result<&'static Route> {
    ROUTES
        .iter()
        .find(|route| match route.0.split_once(' ') {
            Some((route_method, route_path)) => route_method == method && matches(route_path, path),
            None => false,
        })
        .ok_or_else(|| anyhow::anyhow!("unknown Protobuf route: {method} {path}"))
}
pub(crate) fn encode_request(method: &str, path: &str, value: Value) -> anyhow::Result<Vec<u8>> {
    let route = route(method, path)?;
    match route.1 {
        RequestKind::AgentTemplate => encode_wire::<wire::AgentTemplate>(value),
        RequestKind::ClipReq => encode_wire::<wire::ClipReq>(value),
        RequestKind::ConfigPatch => encode_wire::<wire::ConfigPatch>(value),
        RequestKind::CopyPresetReq => encode_wire::<wire::CopyPresetReq>(value),
        RequestKind::CreateAgentTemplateReq => encode_wire::<wire::CreateAgentTemplateReq>(value),
        RequestKind::CreateTaskReq => encode_wire::<wire::CreateTaskReq>(value),
        RequestKind::CreateWorktreeReq => encode_wire::<wire::CreateWorktreeReq>(value),
        RequestKind::Empty => encode_wire::<wire::Empty>(value),
        RequestKind::FileActionReq => encode_wire::<wire::FileActionReq>(value),
        RequestKind::FileReq => encode_wire::<wire::FileReq>(value),
        RequestKind::GrantReq => encode_wire::<wire::GrantReq>(value),
        RequestKind::HighlightReq => encode_wire::<wire::HighlightReq>(value),
        RequestKind::LabelReq => encode_wire::<wire::LabelReq>(value),
        RequestKind::LibraryItem => encode_wire::<wire::LibraryItem>(value),
        RequestKind::PresetRequest => encode_wire::<wire::PresetRequest>(value),
        RequestKind::Project => encode_wire::<wire::Project>(value),
        RequestKind::ProjectPreviewReq => encode_wire::<wire::ProjectPreviewReq>(value),
        RequestKind::ReaderPinnedReq => encode_wire::<wire::ReaderPinnedReq>(value),
        RequestKind::RedrawReq => encode_wire::<wire::RedrawReq>(value),
        RequestKind::RemoveTasksReq => encode_wire::<wire::RemoveTasksReq>(value),
        RequestKind::ReplaceConfigRequest => encode_wire::<wire::ReplaceConfigRequest>(value),
        RequestKind::RunReq => encode_wire::<wire::RunReq>(value),
        RequestKind::RunWhere => encode_wire::<wire::RunWhere>(value),
        RequestKind::SaveTemplateRequest => encode_wire::<wire::SaveTemplateRequest>(value),
        RequestKind::SessionConfig => encode_wire::<wire::SessionConfig>(value),
        RequestKind::SettingsPreviewRequest => encode_wire::<wire::SettingsPreviewRequest>(value),
        RequestKind::SpawnWorkerReq => encode_wire::<wire::SpawnWorkerReq>(value),
        RequestKind::Station => encode_wire::<wire::Station>(value),
        RequestKind::UpdateTaskReq => encode_wire::<wire::UpdateTaskReq>(value),
    }
}
pub(crate) fn decode_response(method: &str, path: &str, value: &[u8]) -> anyhow::Result<Value> {
    let route = route(method, path)?;
    match route.2 {
        ResponseKind::Ack => Ok(serde_json::to_value(wire::Ack::decode(value)?)?),
        ResponseKind::AppsReply => Ok(serde_json::to_value(wire::AppsReply::decode(value)?)?),
        ResponseKind::AudioState => Ok(serde_json::to_value(wire::AudioState::decode(value)?)?),
        ResponseKind::BrowseResult => Ok(serde_json::to_value(wire::BrowseResult::decode(value)?)?),
        ResponseKind::Capabilities => Ok(serde_json::to_value(wire::Capabilities::decode(value)?)?),
        ResponseKind::ConfigResult => Ok(serde_json::to_value(wire::ConfigResult::decode(value)?)?),
        ResponseKind::FileStatResult => {
            Ok(serde_json::to_value(wire::FileStatResult::decode(value)?)?)
        }
        ResponseKind::GitResult => Ok(serde_json::to_value(wire::GitResult::decode(value)?)?),
        ResponseKind::GrantResult => Ok(serde_json::to_value(wire::GrantResult::decode(value)?)?),
        ResponseKind::GrantsReply => Ok(serde_json::to_value(wire::GrantsReply::decode(value)?)?),
        ResponseKind::Health => Ok(serde_json::to_value(wire::Health::decode(value)?)?),
        ResponseKind::HighlightThemes => {
            Ok(serde_json::to_value(wire::HighlightThemes::decode(value)?)?)
        }
        ResponseKind::ImageResult => Ok(serde_json::to_value(wire::ImageResult::decode(value)?)?),
        ResponseKind::JukeboxCatalog => {
            Ok(serde_json::to_value(wire::JukeboxCatalog::decode(value)?)?)
        }
        ResponseKind::LibraryReply => Ok(serde_json::to_value(wire::LibraryReply::decode(value)?)?),
        ResponseKind::OutputResult => Ok(serde_json::to_value(wire::OutputResult::decode(value)?)?),
        ResponseKind::PathResult => Ok(serde_json::to_value(wire::PathResult::decode(value)?)?),
        ResponseKind::PresetsReply => Ok(serde_json::to_value(wire::PresetsReply::decode(value)?)?),
        ResponseKind::Project => Ok(serde_json::to_value(wire::Project::decode(value)?)?),
        ResponseKind::ProjectPreviewResult => Ok(serde_json::to_value(
            wire::ProjectPreviewResult::decode(value)?,
        )?),
        ResponseKind::ProjectsReply => {
            Ok(serde_json::to_value(wire::ProjectsReply::decode(value)?)?)
        }
        ResponseKind::SandboxReport => {
            Ok(serde_json::to_value(wire::SandboxReport::decode(value)?)?)
        }
        ResponseKind::SearchResult => Ok(serde_json::to_value(wire::SearchResult::decode(value)?)?),
        ResponseKind::SessionResult => {
            Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?)
        }
        ResponseKind::SessionView => Ok(serde_json::to_value(wire::SessionView::decode(value)?)?),
        ResponseKind::SessionsReply => {
            Ok(serde_json::to_value(wire::SessionsReply::decode(value)?)?)
        }
        ResponseKind::SettingsPreview => {
            Ok(serde_json::to_value(wire::SettingsPreview::decode(value)?)?)
        }
        ResponseKind::StoredStates => Ok(serde_json::to_value(wire::StoredStates::decode(value)?)?),
        ResponseKind::TaskBatchResult => {
            Ok(serde_json::to_value(wire::TaskBatchResult::decode(value)?)?)
        }
        ResponseKind::TaskResult => Ok(serde_json::to_value(wire::TaskResult::decode(value)?)?),
        ResponseKind::TasksReply => Ok(serde_json::to_value(wire::TasksReply::decode(value)?)?),
        ResponseKind::TemplateResult => {
            Ok(serde_json::to_value(wire::TemplateResult::decode(value)?)?)
        }
        ResponseKind::TemplatesReply => {
            Ok(serde_json::to_value(wire::TemplatesReply::decode(value)?)?)
        }
        ResponseKind::TextResult => Ok(serde_json::to_value(wire::TextResult::decode(value)?)?),
        ResponseKind::UsageSnapshot => {
            Ok(serde_json::to_value(wire::UsageSnapshot::decode(value)?)?)
        }
        ResponseKind::WhereIsReply => Ok(serde_json::to_value(wire::WhereIsReply::decode(value)?)?),
        ResponseKind::WorkerResult => Ok(serde_json::to_value(wire::WorkerResult::decode(value)?)?),
        ResponseKind::Worktree => Ok(serde_json::to_value(wire::Worktree::decode(value)?)?),
        ResponseKind::WorktreeBase => Ok(serde_json::to_value(wire::WorktreeBase::decode(value)?)?),
        ResponseKind::WorktreesReply => {
            Ok(serde_json::to_value(wire::WorktreesReply::decode(value)?)?)
        }
    }
}
#[cfg(test)]
pub(crate) fn decode_request(method: &str, path: &str, value: &[u8]) -> anyhow::Result<Value> {
    let route = route(method, path)?;
    match route.1 {
        RequestKind::AgentTemplate => {
            Ok(serde_json::to_value(wire::AgentTemplate::decode(value)?)?)
        }
        RequestKind::ClipReq => Ok(serde_json::to_value(wire::ClipReq::decode(value)?)?),
        RequestKind::ConfigPatch => Ok(serde_json::to_value(wire::ConfigPatch::decode(value)?)?),
        RequestKind::CopyPresetReq => {
            Ok(serde_json::to_value(wire::CopyPresetReq::decode(value)?)?)
        }
        RequestKind::CreateAgentTemplateReq => Ok(serde_json::to_value(
            wire::CreateAgentTemplateReq::decode(value)?,
        )?),
        RequestKind::CreateTaskReq => {
            Ok(serde_json::to_value(wire::CreateTaskReq::decode(value)?)?)
        }
        RequestKind::CreateWorktreeReq => Ok(serde_json::to_value(
            wire::CreateWorktreeReq::decode(value)?,
        )?),
        RequestKind::Empty => Ok(serde_json::to_value(wire::Empty::decode(value)?)?),
        RequestKind::FileActionReq => {
            Ok(serde_json::to_value(wire::FileActionReq::decode(value)?)?)
        }
        RequestKind::FileReq => Ok(serde_json::to_value(wire::FileReq::decode(value)?)?),
        RequestKind::GrantReq => Ok(serde_json::to_value(wire::GrantReq::decode(value)?)?),
        RequestKind::HighlightReq => Ok(serde_json::to_value(wire::HighlightReq::decode(value)?)?),
        RequestKind::LabelReq => Ok(serde_json::to_value(wire::LabelReq::decode(value)?)?),
        RequestKind::LibraryItem => Ok(serde_json::to_value(wire::LibraryItem::decode(value)?)?),
        RequestKind::PresetRequest => {
            Ok(serde_json::to_value(wire::PresetRequest::decode(value)?)?)
        }
        RequestKind::Project => Ok(serde_json::to_value(wire::Project::decode(value)?)?),
        RequestKind::ProjectPreviewReq => Ok(serde_json::to_value(
            wire::ProjectPreviewReq::decode(value)?,
        )?),
        RequestKind::ReaderPinnedReq => {
            Ok(serde_json::to_value(wire::ReaderPinnedReq::decode(value)?)?)
        }
        RequestKind::RedrawReq => Ok(serde_json::to_value(wire::RedrawReq::decode(value)?)?),
        RequestKind::RemoveTasksReq => {
            Ok(serde_json::to_value(wire::RemoveTasksReq::decode(value)?)?)
        }
        RequestKind::ReplaceConfigRequest => Ok(serde_json::to_value(
            wire::ReplaceConfigRequest::decode(value)?,
        )?),
        RequestKind::RunReq => Ok(serde_json::to_value(wire::RunReq::decode(value)?)?),
        RequestKind::RunWhere => Ok(serde_json::to_value(wire::RunWhere::decode(value)?)?),
        RequestKind::SaveTemplateRequest => Ok(serde_json::to_value(
            wire::SaveTemplateRequest::decode(value)?,
        )?),
        RequestKind::SessionConfig => {
            Ok(serde_json::to_value(wire::SessionConfig::decode(value)?)?)
        }
        RequestKind::SettingsPreviewRequest => Ok(serde_json::to_value(
            wire::SettingsPreviewRequest::decode(value)?,
        )?),
        RequestKind::SpawnWorkerReq => {
            Ok(serde_json::to_value(wire::SpawnWorkerReq::decode(value)?)?)
        }
        RequestKind::Station => Ok(serde_json::to_value(wire::Station::decode(value)?)?),
        RequestKind::UpdateTaskReq => {
            Ok(serde_json::to_value(wire::UpdateTaskReq::decode(value)?)?)
        }
    }
}
#[cfg(test)]
pub(crate) fn encode_response(method: &str, path: &str, value: Value) -> anyhow::Result<Vec<u8>> {
    let route = route(method, path)?;
    match route.2 {
        ResponseKind::Ack => encode_wire::<wire::Ack>(value),
        ResponseKind::AppsReply => encode_wire::<wire::AppsReply>(value),
        ResponseKind::AudioState => encode_wire::<wire::AudioState>(value),
        ResponseKind::BrowseResult => encode_wire::<wire::BrowseResult>(value),
        ResponseKind::Capabilities => encode_wire::<wire::Capabilities>(value),
        ResponseKind::ConfigResult => encode_wire::<wire::ConfigResult>(value),
        ResponseKind::FileStatResult => encode_wire::<wire::FileStatResult>(value),
        ResponseKind::GitResult => encode_wire::<wire::GitResult>(value),
        ResponseKind::GrantResult => encode_wire::<wire::GrantResult>(value),
        ResponseKind::GrantsReply => encode_wire::<wire::GrantsReply>(value),
        ResponseKind::Health => encode_wire::<wire::Health>(value),
        ResponseKind::HighlightThemes => encode_wire::<wire::HighlightThemes>(value),
        ResponseKind::ImageResult => encode_wire::<wire::ImageResult>(value),
        ResponseKind::JukeboxCatalog => encode_wire::<wire::JukeboxCatalog>(value),
        ResponseKind::LibraryReply => encode_wire::<wire::LibraryReply>(value),
        ResponseKind::OutputResult => encode_wire::<wire::OutputResult>(value),
        ResponseKind::PathResult => encode_wire::<wire::PathResult>(value),
        ResponseKind::PresetsReply => encode_wire::<wire::PresetsReply>(value),
        ResponseKind::Project => encode_wire::<wire::Project>(value),
        ResponseKind::ProjectPreviewResult => encode_wire::<wire::ProjectPreviewResult>(value),
        ResponseKind::ProjectsReply => encode_wire::<wire::ProjectsReply>(value),
        ResponseKind::SandboxReport => encode_wire::<wire::SandboxReport>(value),
        ResponseKind::SearchResult => encode_wire::<wire::SearchResult>(value),
        ResponseKind::SessionResult => encode_wire::<wire::SessionResult>(value),
        ResponseKind::SessionView => encode_wire::<wire::SessionView>(value),
        ResponseKind::SessionsReply => encode_wire::<wire::SessionsReply>(value),
        ResponseKind::SettingsPreview => encode_wire::<wire::SettingsPreview>(value),
        ResponseKind::StoredStates => encode_wire::<wire::StoredStates>(value),
        ResponseKind::TaskBatchResult => encode_wire::<wire::TaskBatchResult>(value),
        ResponseKind::TaskResult => encode_wire::<wire::TaskResult>(value),
        ResponseKind::TasksReply => encode_wire::<wire::TasksReply>(value),
        ResponseKind::TemplateResult => encode_wire::<wire::TemplateResult>(value),
        ResponseKind::TemplatesReply => encode_wire::<wire::TemplatesReply>(value),
        ResponseKind::TextResult => encode_wire::<wire::TextResult>(value),
        ResponseKind::UsageSnapshot => encode_wire::<wire::UsageSnapshot>(value),
        ResponseKind::WhereIsReply => encode_wire::<wire::WhereIsReply>(value),
        ResponseKind::WorkerResult => encode_wire::<wire::WorkerResult>(value),
        ResponseKind::Worktree => encode_wire::<wire::Worktree>(value),
        ResponseKind::WorktreeBase => encode_wire::<wire::WorktreeBase>(value),
        ResponseKind::WorktreesReply => encode_wire::<wire::WorktreesReply>(value),
    }
}
