// Generated by tools/protobuf_http.py. Do not edit.
#![allow(dead_code)]
use super::wire;
use prost::Message;
use serde_json::Value;
pub(crate) const CONTENT_TYPE: &str = "application/x-protobuf";
fn matches(pattern: &str, path: &str) -> bool {
    let path = path.split('?').next().unwrap_or(path);
    let a: Vec<_> = pattern.split('/').collect();
    let b: Vec<_> = path.split('/').collect();
    a.len() == b.len() && a.iter().zip(b).all(|(a, b)| a.starts_with(':') || *a == b)
}
pub(crate) fn encode_request(method: &str, path: &str, value: Value) -> anyhow::Result<Vec<u8>> {
    if method == "GET" && matches("/api/health", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions", path) {
        return Ok(serde_json::from_value::<wire::SessionConfig>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/settings/preview", path) {
        return Ok(serde_json::from_value::<wire::SettingsPreviewRequest>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/templates", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/templates", path) {
        return Ok(serde_json::from_value::<wire::SaveTemplateRequest>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/templates/spawnable", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::CreateTaskReq>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/cancel", path) {
        return Ok(serde_json::from_value::<wire::RemoveTasksReq>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/remove", path) {
        return Ok(serde_json::from_value::<wire::RemoveTasksReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/capabilities", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/whereis", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/projects", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/projects", path) {
        return Ok(serde_json::from_value::<wire::Project>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/projects/preview", path) {
        return Ok(serde_json::from_value::<wire::ProjectPreviewReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/library", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/library", path) {
        return Ok(serde_json::from_value::<wire::LibraryItem>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/run", path) {
        return Ok(serde_json::from_value::<wire::RunReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/worktrees", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/worktrees", path) {
        return Ok(serde_json::from_value::<wire::CreateWorktreeReq>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/worktrees/preview", path) {
        return Ok(serde_json::from_value::<wire::CreateWorktreeReq>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/workers", path) {
        return Ok(serde_json::from_value::<wire::SpawnWorkerReq>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/file-action", path) {
        return Ok(serde_json::from_value::<wire::FileActionReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/open-apps", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/grants", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/grants", path) {
        return Ok(serde_json::from_value::<wire::GrantReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/state", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/state/trash", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/presets", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/config", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/config", path) {
        return Ok(serde_json::from_value::<wire::ReplaceConfigRequest>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/config/patch", path) {
        return Ok(serde_json::from_value::<wire::ConfigPatch>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/clipboard", path) {
        return Ok(serde_json::from_value::<wire::ClipReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/text", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::from_value::<wire::ClipReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/primary/text", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/usage", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/audio", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/ncspot", path) {
        return Ok(serde_json::from_value::<wire::RedrawReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/jukebox", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::from_value::<wire::Station>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/browse", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/files/stat", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/read", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/highlight", path) {
        return Ok(serde_json::from_value::<wire::HighlightReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/image", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::FileReq>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::FileReq>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::FileReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/search", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/git", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::SessionConfig>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name/cwd", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name/sandbox", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/start", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/stop", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/restart", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/sessions/:name/label", path) {
        return Ok(serde_json::from_value::<wire::LabelReq>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/state/reset", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/templates/:name", path) {
        return Ok(serde_json::from_value::<wire::AgentTemplate>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/templates/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/templates/:name/create", path) {
        return Ok(serde_json::from_value::<wire::CreateAgentTemplateReq>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::UpdateTaskReq>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Project>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/library/:name", path) {
        return Ok(serde_json::from_value::<wire::LibraryItem>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/library/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/library/:name/run", path) {
        return Ok(serde_json::from_value::<wire::RunWhere>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/worktrees/:id", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/grants/:grantor", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/state/trash/:key/restore", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::from_value::<wire::Station>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/state/:kind/:key", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::from_value::<wire::PresetRequest>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::from_value::<wire::Empty>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/presets/:kind/:name/copy", path) {
        return Ok(serde_json::from_value::<wire::CopyPresetReq>(value)?.encode_to_vec());
    }
    anyhow::bail!("unknown Protobuf route: {method} {path}")
}
pub(crate) fn decode_response(method: &str, path: &str, value: &[u8]) -> anyhow::Result<Value> {
    if method == "GET" && matches("/api/health", path) {
        return Ok(serde_json::to_value(wire::Health::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions", path) {
        return Ok(serde_json::to_value(wire::SessionsReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/settings/preview", path) {
        return Ok(serde_json::to_value(wire::SettingsPreview::decode(value)?)?);
    }
    if method == "GET" && matches("/api/templates", path) {
        return Ok(serde_json::to_value(wire::TemplatesReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/templates", path) {
        return Ok(serde_json::to_value(wire::TemplateResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/templates/spawnable", path) {
        return Ok(serde_json::to_value(wire::TemplatesReply::decode(value)?)?);
    }
    if method == "GET" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::TasksReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::TaskResult::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::Removed::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/cancel", path) {
        return Ok(serde_json::to_value(wire::TasksReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/remove", path) {
        return Ok(serde_json::to_value(wire::Removed::decode(value)?)?);
    }
    if method == "GET" && matches("/api/capabilities", path) {
        return Ok(serde_json::to_value(wire::Capabilities::decode(value)?)?);
    }
    if method == "GET" && matches("/api/whereis", path) {
        return Ok(serde_json::to_value(wire::WhereIsReply::decode(value)?)?);
    }
    if method == "GET" && matches("/api/projects", path) {
        return Ok(serde_json::to_value(wire::ProjectsReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/projects", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/projects/preview", path) {
        return Ok(serde_json::to_value(wire::ProjectPreviewResult::decode(
            value,
        )?)?);
    }
    if method == "GET" && matches("/api/library", path) {
        return Ok(serde_json::to_value(wire::LibraryReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/library", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/run", path) {
        return Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/worktrees", path) {
        return Ok(serde_json::to_value(wire::WorktreesReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/worktrees", path) {
        return Ok(serde_json::to_value(wire::Worktree::decode(value)?)?);
    }
    if method == "POST" && matches("/api/worktrees/preview", path) {
        return Ok(serde_json::to_value(wire::WorktreeBase::decode(value)?)?);
    }
    if method == "POST" && matches("/api/workers", path) {
        return Ok(serde_json::to_value(wire::WorkerResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/file-action", path) {
        return Ok(serde_json::to_value(wire::OutputResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/open-apps", path) {
        return Ok(serde_json::to_value(wire::AppsReply::decode(value)?)?);
    }
    if method == "GET" && matches("/api/grants", path) {
        return Ok(serde_json::to_value(wire::GrantsReply::decode(value)?)?);
    }
    if method == "POST" && matches("/api/grants", path) {
        return Ok(serde_json::to_value(wire::GrantResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/state", path) {
        return Ok(serde_json::to_value(wire::StoredStates::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/state/trash", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/presets", path) {
        return Ok(serde_json::to_value(wire::PresetsReply::decode(value)?)?);
    }
    if method == "GET" && matches("/api/config", path) {
        return Ok(serde_json::to_value(wire::ConfigResult::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/config", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/config/patch", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/clipboard", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/text", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/primary/text", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/usage", path) {
        return Ok(serde_json::to_value(wire::UsageSnapshot::decode(value)?)?);
    }
    if method == "GET" && matches("/api/audio", path) {
        return Ok(serde_json::to_value(wire::AudioState::decode(value)?)?);
    }
    if method == "POST" && matches("/api/ncspot", path) {
        return Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/jukebox", path) {
        return Ok(serde_json::to_value(wire::JukeboxCatalog::decode(value)?)?);
    }
    if method == "GET" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::to_value(wire::JukeboxCatalog::decode(value)?)?);
    }
    if method == "POST" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/browse", path) {
        return Ok(serde_json::to_value(wire::BrowseResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/files/stat", path) {
        return Ok(serde_json::to_value(wire::FileStatResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/read", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/highlight", path) {
        return Ok(serde_json::to_value(wire::TextResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/image", path) {
        return Ok(serde_json::to_value(wire::ImageResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/search", path) {
        return Ok(serde_json::to_value(wire::SearchResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/git", path) {
        return Ok(serde_json::to_value(wire::GitResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::SessionView::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name/cwd", path) {
        return Ok(serde_json::to_value(wire::PathResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name/sandbox", path) {
        return Ok(serde_json::to_value(wire::SandboxReport::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/start", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/stop", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/restart", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/sessions/:name/label", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/state/reset", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/templates/:name", path) {
        return Ok(serde_json::to_value(wire::TemplateResult::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/templates/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/templates/:name/create", path) {
        return Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::TaskResult::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::TaskResult::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::TaskResult::decode(value)?)?);
    }
    if method == "GET" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Project::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/library/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/library/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/library/:name/run", path) {
        return Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/worktrees/:id", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/grants/:grantor", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/state/trash/:key/restore", path) {
        return Ok(serde_json::to_value(wire::SessionResult::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/state/:kind/:key", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    if method == "POST" && matches("/api/presets/:kind/:name/copy", path) {
        return Ok(serde_json::to_value(wire::Ack::decode(value)?)?);
    }
    anyhow::bail!("unknown Protobuf route: {method} {path}")
}
#[cfg(test)]
pub(crate) fn decode_request(method: &str, path: &str, value: &[u8]) -> anyhow::Result<Value> {
    if method == "GET" && matches("/api/health", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions", path) {
        return Ok(serde_json::to_value(wire::SessionConfig::decode(value)?)?);
    }
    if method == "POST" && matches("/api/settings/preview", path) {
        return Ok(serde_json::to_value(wire::SettingsPreviewRequest::decode(
            value,
        )?)?);
    }
    if method == "GET" && matches("/api/templates", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/templates", path) {
        return Ok(serde_json::to_value(wire::SaveTemplateRequest::decode(
            value,
        )?)?);
    }
    if method == "GET" && matches("/api/templates/spawnable", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::CreateTaskReq::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/tasks", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/cancel", path) {
        return Ok(serde_json::to_value(wire::RemoveTasksReq::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/remove", path) {
        return Ok(serde_json::to_value(wire::RemoveTasksReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/capabilities", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/whereis", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/projects", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/projects", path) {
        return Ok(serde_json::to_value(wire::Project::decode(value)?)?);
    }
    if method == "POST" && matches("/api/projects/preview", path) {
        return Ok(serde_json::to_value(wire::ProjectPreviewReq::decode(
            value,
        )?)?);
    }
    if method == "GET" && matches("/api/library", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/library", path) {
        return Ok(serde_json::to_value(wire::LibraryItem::decode(value)?)?);
    }
    if method == "POST" && matches("/api/run", path) {
        return Ok(serde_json::to_value(wire::RunReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/worktrees", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/worktrees", path) {
        return Ok(serde_json::to_value(wire::CreateWorktreeReq::decode(
            value,
        )?)?);
    }
    if method == "POST" && matches("/api/worktrees/preview", path) {
        return Ok(serde_json::to_value(wire::CreateWorktreeReq::decode(
            value,
        )?)?);
    }
    if method == "POST" && matches("/api/workers", path) {
        return Ok(serde_json::to_value(wire::SpawnWorkerReq::decode(value)?)?);
    }
    if method == "POST" && matches("/api/file-action", path) {
        return Ok(serde_json::to_value(wire::FileActionReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/open-apps", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/grants", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/grants", path) {
        return Ok(serde_json::to_value(wire::GrantReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/state", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/state/trash", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/presets", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/config", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/config", path) {
        return Ok(serde_json::to_value(wire::ReplaceConfigRequest::decode(
            value,
        )?)?);
    }
    if method == "PUT" && matches("/api/config/patch", path) {
        return Ok(serde_json::to_value(wire::ConfigPatch::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/clipboard", path) {
        return Ok(serde_json::to_value(wire::ClipReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/text", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::to_value(wire::ClipReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/clipboard/primary/text", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/usage", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/audio", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/ncspot", path) {
        return Ok(serde_json::to_value(wire::RedrawReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/jukebox", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::to_value(wire::Station::decode(value)?)?);
    }
    if method == "GET" && matches("/api/browse", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/files/stat", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/read", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/highlight", path) {
        return Ok(serde_json::to_value(wire::HighlightReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/image", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::FileReq::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::FileReq::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/files", path) {
        return Ok(serde_json::to_value(wire::FileReq::decode(value)?)?);
    }
    if method == "GET" && matches("/api/search", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/git", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::to_value(wire::SessionConfig::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name/cwd", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/sessions/:name/sandbox", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/start", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/stop", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/restart", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/sessions/:name/label", path) {
        return Ok(serde_json::to_value(wire::LabelReq::decode(value)?)?);
    }
    if method == "POST" && matches("/api/sessions/:name/state/reset", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/templates/:name", path) {
        return Ok(serde_json::to_value(wire::AgentTemplate::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/templates/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/templates/:name/create", path) {
        return Ok(serde_json::to_value(wire::CreateAgentTemplateReq::decode(
            value,
        )?)?);
    }
    if method == "GET" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::UpdateTaskReq::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "GET" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Project::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/projects/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/library/:name", path) {
        return Ok(serde_json::to_value(wire::LibraryItem::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/library/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/library/:name/run", path) {
        return Ok(serde_json::to_value(wire::RunWhere::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/worktrees/:id", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/grants/:grantor", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/state/trash/:key/restore", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::to_value(wire::Station::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/state/:kind/:key", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "PUT" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::to_value(wire::PresetRequest::decode(value)?)?);
    }
    if method == "DELETE" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::to_value(wire::Empty::decode(value)?)?);
    }
    if method == "POST" && matches("/api/presets/:kind/:name/copy", path) {
        return Ok(serde_json::to_value(wire::CopyPresetReq::decode(value)?)?);
    }
    anyhow::bail!("unknown Protobuf route: {method} {path}")
}
#[cfg(test)]
pub(crate) fn encode_response(method: &str, path: &str, value: Value) -> anyhow::Result<Vec<u8>> {
    if method == "GET" && matches("/api/health", path) {
        return Ok(serde_json::from_value::<wire::Health>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions", path) {
        return Ok(serde_json::from_value::<wire::SessionsReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/settings/preview", path) {
        return Ok(serde_json::from_value::<wire::SettingsPreview>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/templates", path) {
        return Ok(serde_json::from_value::<wire::TemplatesReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/templates", path) {
        return Ok(serde_json::from_value::<wire::TemplateResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/templates/spawnable", path) {
        return Ok(serde_json::from_value::<wire::TemplatesReply>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::TasksReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::TaskResult>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/tasks", path) {
        return Ok(serde_json::from_value::<wire::Removed>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/cancel", path) {
        return Ok(serde_json::from_value::<wire::TasksReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/remove", path) {
        return Ok(serde_json::from_value::<wire::Removed>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/capabilities", path) {
        return Ok(serde_json::from_value::<wire::Capabilities>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/whereis", path) {
        return Ok(serde_json::from_value::<wire::WhereIsReply>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/projects", path) {
        return Ok(serde_json::from_value::<wire::ProjectsReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/projects", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/projects/preview", path) {
        return Ok(serde_json::from_value::<wire::ProjectPreviewResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/library", path) {
        return Ok(serde_json::from_value::<wire::LibraryReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/library", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/run", path) {
        return Ok(serde_json::from_value::<wire::SessionResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/worktrees", path) {
        return Ok(serde_json::from_value::<wire::WorktreesReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/worktrees", path) {
        return Ok(serde_json::from_value::<wire::Worktree>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/worktrees/preview", path) {
        return Ok(serde_json::from_value::<wire::WorktreeBase>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/workers", path) {
        return Ok(serde_json::from_value::<wire::WorkerResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/file-action", path) {
        return Ok(serde_json::from_value::<wire::OutputResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/open-apps", path) {
        return Ok(serde_json::from_value::<wire::AppsReply>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/grants", path) {
        return Ok(serde_json::from_value::<wire::GrantsReply>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/grants", path) {
        return Ok(serde_json::from_value::<wire::GrantResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/state", path) {
        return Ok(serde_json::from_value::<wire::StoredStates>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/state/trash", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/presets", path) {
        return Ok(serde_json::from_value::<wire::PresetsReply>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/config", path) {
        return Ok(serde_json::from_value::<wire::ConfigResult>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/config", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/config/patch", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/clipboard", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/text", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/clipboard/primary", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/clipboard/primary/text", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/usage", path) {
        return Ok(serde_json::from_value::<wire::UsageSnapshot>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/audio", path) {
        return Ok(serde_json::from_value::<wire::AudioState>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/ncspot", path) {
        return Ok(serde_json::from_value::<wire::SessionResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/jukebox", path) {
        return Ok(serde_json::from_value::<wire::JukeboxCatalog>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::from_value::<wire::JukeboxCatalog>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/jukebox/presets", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/browse", path) {
        return Ok(serde_json::from_value::<wire::BrowseResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/files/stat", path) {
        return Ok(serde_json::from_value::<wire::FileStatResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/read", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/highlight", path) {
        return Ok(serde_json::from_value::<wire::TextResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/image", path) {
        return Ok(serde_json::from_value::<wire::ImageResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/files", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/search", path) {
        return Ok(serde_json::from_value::<wire::SearchResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/git", path) {
        return Ok(serde_json::from_value::<wire::GitResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::SessionView>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/sessions/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name/cwd", path) {
        return Ok(serde_json::from_value::<wire::PathResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/sessions/:name/sandbox", path) {
        return Ok(serde_json::from_value::<wire::SandboxReport>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/start", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/stop", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/restart", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/sessions/:name/label", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/sessions/:name/state/reset", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/templates/:name", path) {
        return Ok(serde_json::from_value::<wire::TemplateResult>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/templates/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/templates/:name/create", path) {
        return Ok(serde_json::from_value::<wire::SessionResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::TaskResult>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::TaskResult>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/tasks/:id", path) {
        return Ok(serde_json::from_value::<wire::TaskResult>(value)?.encode_to_vec());
    }
    if method == "GET" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Project>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/projects/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/library/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/library/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/library/:name/run", path) {
        return Ok(serde_json::from_value::<wire::SessionResult>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/worktrees/:id", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/grants/:grantor", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/state/trash/:key/restore", path) {
        return Ok(serde_json::from_value::<wire::SessionResult>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/jukebox/presets/:id", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/state/:kind/:key", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "PUT" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "DELETE" && matches("/api/presets/:kind/:name", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    if method == "POST" && matches("/api/presets/:kind/:name/copy", path) {
        return Ok(serde_json::from_value::<wire::Ack>(value)?.encode_to_vec());
    }
    anyhow::bail!("unknown Protobuf route: {method} {path}")
}
