// <auto-generated />
// Source: shared/protocol.yaml. Regenerate with `just api-contract`.
#![allow(
    dead_code,
    reason = "generated bindings are shared across daemon and mod clients"
)]

pub(crate) const TOKEN_HEADER: &str = "x-slop-token";
pub(crate) const SESSION_HEADER: &str = "x-slop-session";
pub(crate) const WS_PATH: &str = "/ws";

pub(crate) mod routes {
    pub(crate) const HEALTH: &str = "/api/health";
    pub(crate) const SESSIONS: &str = "/api/sessions";
    pub(crate) const SESSION: &str = "/api/sessions/:name";
    pub(crate) const SESSION_UPDATE: &str = "/api/sessions/:name";
    pub(crate) const SESSION_CWD: &str = "/api/sessions/:name/cwd";
    pub(crate) const SESSION_SANDBOX: &str = "/api/sessions/:name/sandbox";
    pub(crate) const SESSION_START: &str = "/api/sessions/:name/start";
    pub(crate) const SESSION_STOP: &str = "/api/sessions/:name/stop";
    pub(crate) const SESSION_RESTART: &str = "/api/sessions/:name/restart";
    pub(crate) const SESSION_LABEL: &str = "/api/sessions/:name/label";
    pub(crate) const SESSION_READER_PINNED: &str = "/api/sessions/:name/reader-pinned";
    pub(crate) const SESSION_STATE_RESET: &str = "/api/sessions/:name/state/reset";
    pub(crate) const SETTINGS_PREVIEW: &str = "/api/settings/preview";
    pub(crate) const TEMPLATES: &str = "/api/templates";
    pub(crate) const SPAWNABLE_TEMPLATES: &str = "/api/templates/spawnable";
    pub(crate) const TEMPLATE: &str = "/api/templates/:name";
    pub(crate) const TEMPLATE_CREATE: &str = "/api/templates/:name/create";
    pub(crate) const TASKS: &str = "/api/tasks";
    pub(crate) const TASKS_CANCEL: &str = "/api/tasks/cancel";
    pub(crate) const TASKS_REMOVE: &str = "/api/tasks/remove";
    pub(crate) const TASK: &str = "/api/tasks/:id";
    pub(crate) const CAPABILITIES: &str = "/api/capabilities";
    pub(crate) const WHEREIS: &str = "/api/whereis";
    pub(crate) const PROJECTS: &str = "/api/projects";
    pub(crate) const PROJECT_PREVIEW: &str = "/api/projects/preview";
    pub(crate) const PROJECT: &str = "/api/projects/:name";
    pub(crate) const LIBRARY: &str = "/api/library";
    pub(crate) const LIBRARY_ITEM: &str = "/api/library/:name";
    pub(crate) const LIBRARY_ITEM_RUN: &str = "/api/library/:name/run";
    pub(crate) const RUN: &str = "/api/run";
    pub(crate) const WORKTREES: &str = "/api/worktrees";
    pub(crate) const WORKTREE_PREVIEW: &str = "/api/worktrees/preview";
    pub(crate) const WORKTREE: &str = "/api/worktrees/:id";
    pub(crate) const WORKERS: &str = "/api/workers";
    pub(crate) const FILE_ACTION: &str = "/api/file-action";
    pub(crate) const OPEN_APPS: &str = "/api/open-apps";
    pub(crate) const GRANTS: &str = "/api/grants";
    pub(crate) const GRANTOR: &str = "/api/grants/:grantor";
    pub(crate) const STATE: &str = "/api/state";
    pub(crate) const STATE_TRASH: &str = "/api/state/trash";
    pub(crate) const STATE_ITEM: &str = "/api/state/:kind/:key";
    pub(crate) const STATE_TRASH_RESTORE: &str = "/api/state/trash/:key/restore";
    pub(crate) const PRESETS: &str = "/api/presets";
    pub(crate) const PRESET: &str = "/api/presets/:kind/:name";
    pub(crate) const PRESET_COPY: &str = "/api/presets/:kind/:name/copy";
    pub(crate) const CONFIG: &str = "/api/config";
    pub(crate) const CONFIG_PATCH: &str = "/api/config/patch";
    pub(crate) const CLIPBOARD: &str = "/api/clipboard";
    pub(crate) const CLIPBOARD_TEXT: &str = "/api/clipboard/text";
    pub(crate) const CLIPBOARD_PRIMARY: &str = "/api/clipboard/primary";
    pub(crate) const CLIPBOARD_PRIMARY_TEXT: &str = "/api/clipboard/primary/text";
    pub(crate) const USAGE: &str = "/api/usage";
    pub(crate) const AUDIO: &str = "/api/audio";
    pub(crate) const NCSPOT: &str = "/api/ncspot";
    pub(crate) const JUKEBOX: &str = "/api/jukebox";
    pub(crate) const JUKEBOX_PRESETS: &str = "/api/jukebox/presets";
    pub(crate) const JUKEBOX_PRESET: &str = "/api/jukebox/presets/:id";
    pub(crate) const BROWSE: &str = "/api/browse";
    pub(crate) const FILE_STAT: &str = "/api/files/stat";
    pub(crate) const READ: &str = "/api/read";
    pub(crate) const HIGHLIGHT: &str = "/api/highlight";
    pub(crate) const HIGHLIGHT_THEMES: &str = "/api/highlight/themes";
    pub(crate) const IMAGE: &str = "/api/image";
    pub(crate) const FILES: &str = "/api/files";
    pub(crate) const SEARCH: &str = "/api/search";
    pub(crate) const GIT: &str = "/api/git";
}

pub(crate) mod events {
    pub(crate) const CAPABILITIES: &str = "capabilities";
    pub(crate) const SESSIONS: &str = "sessions";
    pub(crate) const PROJECTS: &str = "projects";
    pub(crate) const LIBRARY: &str = "library";
    pub(crate) const SCREEN: &str = "screen";
    pub(crate) const USAGE: &str = "usage";
    pub(crate) const AUDIO: &str = "audio";
    pub(crate) const JUKEBOX: &str = "jukebox";
}

pub(crate) mod messages {
    pub(crate) const REDRAW: &str = "redraw";
    pub(crate) const SUB: &str = "sub";
    pub(crate) const UNSUB: &str = "unsub";
    pub(crate) const KEYS: &str = "keys";
    pub(crate) const RESIZE: &str = "resize";
    pub(crate) const SCROLL: &str = "scroll";
    pub(crate) const MOUSE: &str = "mouse";
    pub(crate) const PASTE: &str = "paste";
    pub(crate) const BREADCRUMB: &str = "breadcrumb";
    pub(crate) const AUDIO: &str = "audio";
}

pub(crate) mod enums {
    pub(crate) mod agent_state {
        pub(crate) const DOWN: &str = "down";
        pub(crate) const WORKING: &str = "working";
        pub(crate) const WAITING: &str = "waiting";
        pub(crate) const IDLE: &str = "idle";
    }
    pub(crate) mod network_mode {
        pub(crate) const NONE: &str = "none";
        pub(crate) const PRIVATE: &str = "private";
        pub(crate) const HOST: &str = "host";
    }
    pub(crate) mod mount_mode {
        pub(crate) const RO: &str = "ro";
        pub(crate) const RW: &str = "rw";
        pub(crate) const CACHE: &str = "cache";
    }
    pub(crate) mod dns_mode {
        pub(crate) const RESOLVED: &str = "resolved";
        pub(crate) const SERVERS: &str = "servers";
    }
    pub(crate) mod library_kind {
        pub(crate) const PROMPT: &str = "prompt";
        pub(crate) const SHELL: &str = "shell";
        pub(crate) const BREADCRUMB: &str = "breadcrumb";
        pub(crate) const FA: &str = "fa";
    }
    pub(crate) mod library_link {
        pub(crate) const PROJECT: &str = "project";
        pub(crate) const TEMP: &str = "temp";
        pub(crate) const ASK: &str = "ask";
    }
    pub(crate) mod file_action_mode {
        pub(crate) const ASK: &str = "ask";
        pub(crate) const SHOW_RESULT: &str = "show_result";
        pub(crate) const OPEN_TERMINAL: &str = "open_terminal";
        pub(crate) const NOTHING: &str = "nothing";
    }
    pub(crate) mod task_status {
        pub(crate) const QUEUED: &str = "queued";
        pub(crate) const ACCEPTED: &str = "accepted";
        pub(crate) const WORKING: &str = "working";
        pub(crate) const DONE: &str = "done";
        pub(crate) const FAILED: &str = "failed";
        pub(crate) const CANCELED: &str = "canceled";
    }
    pub(crate) mod usage_unit {
        pub(crate) const PCT: &str = "pct";
        pub(crate) const USD: &str = "usd";
    }
}

pub(crate) const HOST_IDENTITY: &str = "host";
pub(crate) const TEMPLATE_VERSION_QUERY: &str = "version";
pub(crate) const TERMINAL_MIN_COLS: u16 = 20;
pub(crate) const TERMINAL_MAX_COLS: u16 = 500;
pub(crate) const TERMINAL_MIN_ROWS: u16 = 5;
pub(crate) const TERMINAL_MAX_ROWS: u16 = 200;
