// <auto-generated />
// Source: shared/usage.yaml; regenerate with `make api-contract`.
#![allow(dead_code)]

pub(crate) const CLAUDE_SESSION: &str = "claude_session";
pub(crate) const CLAUDE_WEEK: &str = "claude_week";
pub(crate) const CLAUDE_SPEND: &str = "claude_spend";
pub(crate) const OPENAI_SESSION: &str = "openai_session";
pub(crate) const OPENAI_WEEK: &str = "openai_week";
pub(crate) const OPENROUTER_BALANCE: &str = "openrouter_balance";
