using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SlopWorld
{
    // The daemon owns the file and hands these over parsed, so nothing in the mod has
    // to speak TOML. This is a read model for the settings pages, not a second schema for
    // the whole daemon config. Writes are partial patches, so fields not represented here
    // remain untouched on the server.
    public class DaemonConfig
    {
        public const string DefaultInstructionsTemplate =
            "# SlopWorld agent context\n\n" +
            "Read the project's `README.md` and any applicable `AGENTS.md` files for project " +
            "instructions. This generated `{{ file }}` is mounted at `{{ mount_path }}` and is " +
            "runtime context, not a replacement for them.\n\n" +
            "{{ runtime_context }}\n";
        public const string DefaultInstructionsBreadcrumb = WireContract.DefaultInstructionsBreadcrumb;
        public const string DefaultWorkerPrompt = WireContract.DefaultWorkerPrompt;
        public const string DefaultSummaryPrompt = WireContract.DefaultSummaryPrompt;

        public int UsagePollSecs = WireContract.UsagePollSecs;
        // One entry per usage window. A zero interval means the global interval applies.
        public Dictionary<string, UsageItemConfig> UsageItems =
            new Dictionary<string, UsageItemConfig>();
        // Where the daemon looks for Claude Code's OAuth token.
        public string ClaudeCredentials = WireContract.DefaultClaudeCredentials;
        // Blank means the daemon reads OPENROUTER_API_KEY out of its own environment.
        public string OpenrouterKeyFile = "";
        // Codex's ChatGPT login carries the token the usage endpoint needs. Unlike a key,
        // it is a live login file that the daemon reads fresh and never sends to the mod.
        public string OpenaiCredentials = WireContract.DefaultOpenaiCredentials;
        // Agent prompt-derived titles use a separate OpenRouter request.
        public string AgentTitles = "never";
        public string TitleModel = WireContract.DefaultTitleModel;
        public string SummaryPrompt = DefaultSummaryPrompt;
        public int TitleMinChars = WireContract.DefaultTitleMinChars;
        // Pi titles are generated by slopd before input reaches the sandbox.
        public string PiTitles = "always";
        // Task summaries are generated once for each durable delegated task.
        public string TaskSummaries = "never";
        public bool ExperimentalBreadcrumbs;
        public bool ExperimentalInstructions;
        // The generated project-root runtime manifest. The body is a Markdown template, with
        // {{ runtime_context }} expanding to the daemon's live snapshot.
        public string InstructionsTemplate = DefaultInstructionsTemplate;
        public string InstructionsMountPath = WireContract.DefaultInstructionsMountPath;
        public string InstructionsBreadcrumb = DefaultInstructionsBreadcrumb;
        public bool InstructionsBreadcrumbEnabled = WireContract.DefaultInstructionsBreadcrumbEnabled;
        public string WorkerPrompt = DefaultWorkerPrompt;

        public string RenderInstructionsBreadcrumb(string project)
        {
            var values = new Dictionary<string, string>
            {
                ["project"] = project ?? "",
                ["mount_path"] = InstructionsMountPath ?? "",
                ["file"] = WireContract.DefaultInstructionsMountPath,
            };
            return RenderTemplate(InstructionsBreadcrumb ?? "", values);
        }

        static string RenderTemplate(string template, Dictionary<string, string> values)
        {
            var output = new StringBuilder(template.Length);
            int offset = 0;
            while (offset < template.Length)
            {
                int start = template.IndexOf("{{", offset, System.StringComparison.Ordinal);
                if (start < 0)
                {
                    output.Append(template, offset, template.Length - offset);
                    break;
                }
                output.Append(template, offset, start - offset);
                int end = template.IndexOf("}}", start + 2, System.StringComparison.Ordinal);
                if (end < 0)
                {
                    output.Append(template, start, template.Length - start);
                    break;
                }
                string key = template.Substring(start + 2, end - start - 2).Trim();
                if (values.TryGetValue(key, out string value))
                    output.Append(value);
                else
                    output.Append(template, start, end + 2 - start);
                offset = end + 2;
            }
            return output.ToString();
        }

        // Agent and Shell name command presets. AgentShell is the shell advertised inside
        // sandboxed agent sessions; it is separate from the shell errand preset.
        public string Agent = WireContract.DefaultAgent;
        public string AgentShell = WireContract.DefaultAgentShell;
        public string Shell = WireContract.DefaultShell;
        public string Pager = WireContract.DefaultPager;
        public string Editor = WireContract.DefaultEditor;
        public string Highlighter = WireContract.DefaultHighlighter;

        public static DaemonConfig FromJson(JVal v)
        {
            var d = v["daemon"];
            var f = v["defaults"];
            var c = v["commands"];
            var i = d["instructions"];
            return new DaemonConfig
            {
                ExperimentalBreadcrumbs = d["experimental_breadcrumbs"].AsBool(
                    d["experimental"].AsBool(false)),
                ExperimentalInstructions = d["experimental_instructions"].AsBool(
                    d["experimental"].AsBool(false)),
                UsagePollSecs = d["usage_poll_secs"].AsInt(WireContract.UsagePollSecs),
                UsageItems = UsageItemsFromJson(d["usage_items"]),
                ClaudeCredentials =
                    d["claude_credentials"].AsString(WireContract.DefaultClaudeCredentials),
                OpenrouterKeyFile = d["openrouter_key_file"].AsString(),
                OpenaiCredentials = d["openai_credentials"].AsString(WireContract.DefaultOpenaiCredentials),
                AgentTitles = d["agent_titles"].AsString("never"),
                TitleModel = d["title_model"].AsString(WireContract.DefaultTitleModel),
                SummaryPrompt = d["summary_prompt"].AsString(DefaultSummaryPrompt),
                TitleMinChars = d["title_min_chars"].AsInt(WireContract.DefaultTitleMinChars),
                PiTitles = d["pi_titles"].AsString("always"),
                TaskSummaries = d["task_summaries"].AsString("never"),
                InstructionsTemplate = i["template"].AsString(DefaultInstructionsTemplate),
                InstructionsMountPath = i["mount_path"].AsString(WireContract.DefaultInstructionsMountPath),
                InstructionsBreadcrumb =
                    i["breadcrumb"].AsString(DefaultInstructionsBreadcrumb),
                InstructionsBreadcrumbEnabled = i["breadcrumb_enabled"].AsBool(WireContract.DefaultInstructionsBreadcrumbEnabled),
                WorkerPrompt = i["worker_prompt"].AsString(DefaultWorkerPrompt),

                Agent = f["agent"].AsString(WireContract.DefaultAgent),
                AgentShell = f["agent_shell"].AsString(WireContract.DefaultAgentShell),
                Shell = f["shell"].AsString(WireContract.DefaultShell),
                Pager = c["pager"].AsString(WireContract.DefaultPager),
                Editor = c["editor"].AsString(WireContract.DefaultEditor),
                Highlighter = c["highlighter"].AsString(WireContract.DefaultHighlighter),
            };
        }

        public class UsageItemConfig
        {
            public bool Poll = true;
            // Zero is the client-side representation of an omitted TOML interval.
            public int IntervalSecs;
        }

        static Dictionary<string, UsageItemConfig> UsageItemsFromJson(JVal value)
        {
            var items = new Dictionary<string, UsageItemConfig>();
            if (value.Obj == null) return items;

            foreach (var pair in value.Obj)
                items[pair.Key] = new UsageItemConfig
                {
                    Poll = pair.Value["poll"].AsBool(true),
                    IntervalSecs = pair.Value["interval_secs"].AsInt(0),
                };
            return items;
        }

        // This deliberately omits bind, token, projects, sessions, state rules and sandbox
        // presets. The daemon deep-merges this object before validating it.
        public string ToPatchJson(string baseline = null)
        {
            var before = baseline == null ? null : JVal.Parse(baseline);
            var daemon = before?["daemon"];
            return PatchObject(before,
                "daemon", PatchObject(daemon,
                    "experimental_breadcrumbs", JVal.B(ExperimentalBreadcrumbs),
                    "experimental_instructions", JVal.B(ExperimentalInstructions),
                    "usage_poll_secs", UsagePollSecs.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    "usage_items", UsageItemsJson(daemon?["usage_items"]),
                    "claude_credentials", JVal.Q(ClaudeCredentials),
                    "openrouter_key_file", JVal.Q(OpenrouterKeyFile),
                    "openai_credentials", JVal.Q(OpenaiCredentials),
                    "agent_titles", JVal.Q(AgentTitles),
                    "title_model", JVal.Q(TitleModel),
                    "summary_prompt", JVal.Q(SummaryPrompt),
                    "title_min_chars", TitleMinChars.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    "pi_titles", JVal.Q(PiTitles),
                    "task_summaries", JVal.Q(TaskSummaries),
                    "instructions", PatchObject(daemon?["instructions"],
                        "template", JVal.Q(InstructionsTemplate),
                        "mount_path", JVal.Q(InstructionsMountPath),
                        "breadcrumb", JVal.Q(InstructionsBreadcrumb),
                        "breadcrumb_enabled", JVal.B(InstructionsBreadcrumbEnabled),
                        "worker_prompt", JVal.Q(WorkerPrompt))),
                "defaults", PatchObject(before?["defaults"],
                    "agent", JVal.Q(Agent), "agent_shell", JVal.Q(AgentShell),
                    "shell", JVal.Q(Shell)),
                "commands", PatchObject(before?["commands"],
                    "pager", JVal.Q(Pager), "editor", JVal.Q(Editor),
                    "highlighter", JVal.Q(Highlighter)));
        }

        // Nested objects have already been reduced to changed leaves. Retain the original
        // scalar JSON so booleans, numbers and escaped strings keep their wire types.
        static string PatchObject(JVal baseline, params string[] fields)
        {
            var parts = new List<string>();
            for (int i = 0; i < fields.Length; i += 2)
            {
                string value = fields[i + 1];
                var current = JVal.Parse(value);
                if (baseline != null)
                {
                    var previous = baseline[fields[i]];
                    if (current.Obj != null ? current.Obj.Count == 0 :
                        !previous.IsNull && current.Str == previous.Str &&
                        current.Num == previous.Num && current.Bool == previous.Bool)
                        continue;
                }
                parts.Add(JVal.Q(fields[i]) + ":" + value);
            }
            return "{" + string.Join(",", parts.ToArray()) + "}";
        }

        string UsageItemsJson(JVal baseline)
        {
            var parts = new List<string>();
            foreach (var pair in UsageItems)
            {
                var item = pair.Value ?? new UsageItemConfig();
                // Zero is explicit here so a previously saved per-item override can be
                // cleared through the daemon's deep-merge patch.
                string interval = item.IntervalSecs > 0
                    ? item.IntervalSecs.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : "0";
                string changes = PatchObject(baseline?[pair.Key],
                    "poll", JVal.B(item.Poll), "interval_secs", interval);
                if (baseline == null || changes != "{}")
                    parts.Add(JVal.Q(pair.Key) + ":" + changes);
            }
            return "{" + string.Join(",", parts.ToArray()) + "}";
        }

        // One entry per line, which is how the GUI edits these lists.
        public static string Lines(List<string> items) =>
            string.Join("\n", items.ToArray());

        public static List<string> Split(string text) =>
            (text ?? "").Split('\n')
                .Select(l => l.Trim())
                .Where(l => l.Length > 0)
                .ToList();
    }
}
