#!/usr/bin/env python3
"""Generate CLI and test adapters from the route payload inventory. IPC carries no JSON text."""

import json
import re
import subprocess

from tools import ROOT
from tools.generated_files import write_if_changed
from tools.protocol.wire_contract import load


def validate_route_precedence(rows):
    """Reject intersecting patterns unless one is strictly more specific."""
    for index, (method, path, *_types) in enumerate(rows):
        left = path.split('/')
        for other_method, other_path, *_ in rows[index + 1 :]:
            right = other_path.split('/')
            if method != other_method or len(left) != len(right):
                continue
            if any(a != b and not a.startswith(':') and not b.startswith(':') for a, b in zip(left, right)):
                continue
            left_specific = any(not a.startswith(':') and b.startswith(':') for a, b in zip(left, right))
            right_specific = any(a.startswith(':') and not b.startswith(':') for a, b in zip(left, right))
            if left_specific == right_specific:
                raise ValueError(f'ambiguous {method} routes: {path} and {other_path}')


def main(output_root=ROOT) -> None:
    protocol = load(ROOT / 'shared')['protocol']
    schema = set(re.findall(r'\bmessage\s+(\w+)\s*\{', (ROOT / 'shared/slopworld.proto').read_text()))
    rows = []
    for name, route in protocol['http']['routes'].items():
        if set(route['protobuf']) != set(route['methods']):
            raise ValueError(f'{name}: payload methods differ from route methods')
        for method, (request, response) in route['protobuf'].items():
            if request not in schema or response not in schema:
                raise ValueError(f'{name}: unknown Protobuf payload type')
            rows.append((method, route['path'], request, response))

    # Static routes must win over parameter routes of equal depth. Keep this order in
    # the single lookup table so every adapter uses the same route selection.
    validate_route_precedence(rows)
    rows.sort(key=lambda row: row[1].count(':'))
    request_kinds = sorted({row[2] for row in rows})
    response_kinds = sorted({row[3] for row in rows})

    out = [
        '// Generated by tools/protocol/protobuf_http.py. Do not edit.',
        '#![allow(',
        '    dead_code,',
        '    reason = "generated route adapters are shared across daemon and mod clients"',
        ')]',
        'use super::wire;',
        'use prost::Message;',
        'use serde_json::Value;',
        'fn encode_wire<T>(value: Value) -> anyhow::Result<Vec<u8>>',
        'where',
        '    T: serde::de::DeserializeOwned + Message,',
        '{',
        '    Ok(serde_json::from_value::<T>(value)?.encode_to_vec())',
        '}',
        'pub(crate) const CONTENT_TYPE: &str = "application/x-protobuf";',
        'fn matches(pattern: &str, path: &str) -> bool {',
        "    let path = path.split('?').next().unwrap_or(path);",
        "    let a: Vec<_> = pattern.split('/').collect();",
        "    let b: Vec<_> = path.split('/').collect();",
        "    a.len() == b.len() && a.iter().zip(b).all(|(a,b)| a.starts_with(':') || *a == b)",
        '}',
        '#[derive(Clone, Copy)]',
        'enum RequestKind {',
    ]
    out.extend(f'    {kind},' for kind in request_kinds)
    out.extend(['}', '#[derive(Clone, Copy)]', 'enum ResponseKind {'])
    out.extend(f'    {kind},' for kind in response_kinds)
    out.extend(
        [
            '}',
            # Short aliases keep generated route rows compact.
            'use RequestKind as Req;',
            'use ResponseKind as Resp;',
            "type Route = (&'static str, RequestKind, ResponseKind);",
            'const ROUTES: &[Route] = &[',
        ]
    )
    for method, path, request, response in rows:
        route_key = json.dumps(f'{method} {path}')
        out.append(f'    ({route_key}, Req::{request}, Resp::{response}),')
    out.extend(
        [
            '];',
            "fn route(method: &str, path: &str) -> anyhow::Result<&'static Route> {",
            '    ROUTES',
            '        .iter()',
            "        .find(|route| match route.0.split_once(' ') {",
            '            Some((route_method, route_path)) => {',
            '                route_method == method && matches(route_path, path)',
            '            }',
            '            None => false,',
            '        })',
            '        .ok_or_else(|| anyhow::anyhow!("unknown Protobuf route: {method} {path}"))',
            '}',
        ]
    )

    def emit_dispatch(name, kind_index, kind_name, kinds, input_type, output_type, encode, test_only=False):
        if test_only:
            out.append('#[cfg(test)]')
        out.append(
            f'pub(crate) fn {name}(method: &str, path: &str, value: {input_type}) -> anyhow::Result<{output_type}> {{'
        )
        out.append('    let route = route(method, path)?;')
        out.append(f'    match route.{kind_index} {{')
        for kind in kinds:
            if encode:
                expression = f'encode_wire::<wire::{kind}>(value)'
            else:
                expression = f'serde_json::to_value(wire::{kind}::decode(value)?)?'
            if encode:
                out.append(f'        {kind_name}Kind::{kind} => {expression},')
            else:
                out.append(f'        {kind_name}Kind::{kind} => Ok({expression}),')
        out.extend(['    }', '}'])

    emit_dispatch('encode_request', '1', 'Request', request_kinds, 'Value', 'Vec<u8>', True)
    emit_dispatch('decode_response', '2', 'Response', response_kinds, '&[u8]', 'Value', False)
    emit_dispatch('decode_request', '1', 'Request', request_kinds, '&[u8]', 'Value', False, True)
    emit_dispatch('encode_response', '2', 'Response', response_kinds, 'Value', 'Vec<u8>', True, True)

    formatted = subprocess.run(
        ['rustfmt', '--edition', '2024'],
        input='\n'.join(out) + '\n',
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    write_if_changed(output_root / 'slopd/src/shared/http_wire.rs', formatted.encode())


if __name__ == '__main__':
    main()
