#!/usr/bin/env python3
"""Generate Rust and C# bindings from the shared wire protocol.

Rust code owns daemon defaults and usage policy.
The API exposes these values as read models.
Generated client bindings do not include the policy. This prevents older mods from applying a stale copy.
"""

from __future__ import annotations

import re
from pathlib import Path

from tools import ROOT
from tools.generated_files import write_if_changed

try:
    import yaml
except ImportError as exc:  # pragma: no cover - exercised by a missing developer dependency
    raise SystemExit(
        'just api-contract requires PyYAML. Run just sync-tools or invoke this module through uv run --locked python'
    ) from exc

SHARED = ROOT / 'shared'


def rust_header(source: str) -> list[str]:
    return [
        '// <auto-generated />',
        f'// Source: shared/{source}.yaml. Regenerate with `just api-contract`.',
        '#![allow(',
        '    dead_code,',
        '    reason = "generated bindings are shared across daemon and mod clients"',
        ')]',
        '',
    ]


def pascal(name: str) -> str:
    return ''.join(part[:1].upper() + part[1:] for part in re.split(r'[_-]+', name))


def upper(name: str) -> str:
    return name.upper().replace('-', '_')


class UniqueLoader(yaml.SafeLoader):
    """Reject duplicate keys instead of silently replacing shared definitions."""


def unique_mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if key in result:
            raise ValueError(f'duplicate key {key!r} at {key_node.start_mark}')
        result[key] = loader.construct_object(value_node)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def load(directory: Path = SHARED) -> dict:
    data = {}
    expected = {'version', 'http', 'websocket', 'enums', 'constants'}
    path = directory / 'protocol.yaml'
    document = yaml.load(path.read_text(), Loader=UniqueLoader)
    if not isinstance(document, dict) or set(document) != expected:
        raise ValueError(f'{path}: expected sections {sorted(expected)}')
    if type(document['version']) is not int or document['version'] != 2:
        raise ValueError(f'{path}: unsupported shared definition version')
    for section in expected - {'version'}:
        if not isinstance(document[section], dict) or not document[section]:
            raise ValueError(f'{path}: {section} must be a nonempty mapping')
    data['protocol'] = document
    validate(data)
    return data


def validate(data: dict) -> None:
    protocol = data['protocol']
    routes = protocol['http'].get('routes')
    if not isinstance(routes, dict) or not routes:
        raise ValueError('protocol definition has no HTTP routes')
    for name, route in routes.items():
        if (
            not isinstance(route, dict)
            or not {'path', 'methods', 'scope', 'protobuf'} <= route.keys()
            or not isinstance(route['path'], str)
            or not route['path'].startswith('/')
            or not isinstance(route['methods'], list)
            or not route['methods']
            or any(
                not isinstance(m, str) or m not in {'GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', 'TRACE'}
                for m in route['methods']
            )
            or not isinstance(route['scope'], str)
            or route['scope'] not in {'root', 'scoped'}
        ):
            raise ValueError(f'invalid route {name}')
        payloads = route['protobuf']
        if (
            not isinstance(payloads, dict)
            or set(payloads) != set(route['methods'])
            or len(route['methods']) != len(set(route['methods']))
        ):
            raise ValueError(f'{name}: invalid Protobuf method mapping')
        for pair in payloads.values():
            if (
                not isinstance(pair, list)
                or len(pair) != 2
                or any(
                    not isinstance(value, str) or not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', value) for value in pair
                )
            ):
                raise ValueError(f'{name}: expected Protobuf request/response names')
    websocket = protocol['http'].get('websocket')
    headers = protocol['http'].get('headers')
    if (
        not isinstance(websocket, dict)
        or not isinstance(websocket.get('path'), str)
        or not websocket['path'].startswith('/')
    ):
        raise ValueError('invalid HTTP WebSocket declaration')
    if not isinstance(headers, dict) or any(
        not isinstance(headers.get(key), str) or not headers[key] for key in ('token', 'session')
    ):
        raise ValueError('invalid HTTP headers')
    for name, values in {**protocol['websocket'], **protocol['enums']}.items():
        if (
            not isinstance(values, list)
            or not values
            or any(not isinstance(v, str) for v in values)
            or len(values) != len(set(values))
        ):
            raise ValueError(f'{name}: expected unique string values')
    for name, value in protocol['constants'].items():
        if type(value) not in (str, bool, int):
            raise ValueError(f'protocol.{name}: expected string, boolean or integer')
        if type(value) is int:
            maximum = (
                65535
                if name in {'terminal_min_cols', 'terminal_max_cols', 'terminal_min_rows', 'terminal_max_rows'}
                else 2147483647
            )
            if not 0 <= value <= maximum:
                raise ValueError(f'protocol.{name}: integer must be between 0 and {maximum}')
    validate_names(routes, 'routes')
    validate_names(protocol['constants'], 'constants')
    validate_names(protocol['enums'], 'enum modules', allow_hyphens=False)
    for section, values in {**protocol['websocket'], **protocol['enums']}.items():
        validate_names(values, section)


def validate_names(names, section, *, allow_hyphens=True):
    """Keep normalized identifiers legal and unique in both generated languages."""
    rust_names, cs_names = set(), set()
    pattern = r'[A-Za-z_][A-Za-z0-9_-]*' if allow_hyphens else r'[A-Za-z_][A-Za-z0-9_]*'
    for name in names:
        if not isinstance(name, str) or not re.fullmatch(pattern, name) or not pascal(name):
            raise ValueError(f'{section}: invalid identifier {name!r}')
        rust_name, cs_name = upper(name), pascal(name)
        if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', cs_name):
            raise ValueError(f'{section}: invalid generated identifier {name!r}')
        if not allow_hyphens and name in {
            'as',
            'async',
            'await',
            'break',
            'const',
            'continue',
            'crate',
            'dyn',
            'else',
            'enum',
            'extern',
            'false',
            'fn',
            'for',
            'if',
            'impl',
            'in',
            'let',
            'loop',
            'match',
            'mod',
            'move',
            'mut',
            'pub',
            'ref',
            'return',
            'self',
            'Self',
            'static',
            'struct',
            'super',
            'trait',
            'true',
            'type',
            'unsafe',
            'use',
            'where',
            'while',
            'abstract',
            'become',
            'box',
            'do',
            'final',
            'gen',
            'macro',
            'override',
            'priv',
            'try',
            'typeof',
            'unsized',
            'virtual',
            'yield',
        }:
            raise ValueError(f'{section}: reserved Rust identifier {name!r}')
        if rust_name in rust_names or cs_name in cs_names:
            raise ValueError(f'{section}: duplicate generated identifier {name!r}')
        rust_names.add(rust_name)
        cs_names.add(cs_name)


def rust_string(value: str) -> str:
    return source_string(value, rust=True)


def cs_string(value: str) -> str:
    return source_string(value, rust=False)


def source_string(value: str, *, rust: bool) -> str:
    escapes = {'\\': '\\\\', '"': '\\"', '\n': '\\n', '\r': '\\r', '\t': '\\t'}

    def escape(char):
        if char in escapes:
            return escapes[char]
        if ord(char) < 32 or ord(char) == 127:
            return '\\u{' + f'{ord(char):x}' + '}' if rust else '\\u' + f'{ord(char):04x}'
        return char

    return '"' + ''.join(escape(char) for char in value) + '"'


def rust(data: dict) -> str:
    lines = rust_header('protocol')
    lines += [
        'pub(crate) const TOKEN_HEADER: &str = ' + rust_string(data['http']['headers']['token']) + ';',
        'pub(crate) const SESSION_HEADER: &str = ' + rust_string(data['http']['headers']['session']) + ';',
        'pub(crate) const WS_PATH: &str = ' + rust_string(data['http']['websocket']['path']) + ';',
        '',
        'pub(crate) mod routes {',
    ]
    for name, route in data['http']['routes'].items():
        lines.append(f'    pub(crate) const {upper(name)}: &str = {rust_string(route["path"])};')
    lines += ['}', '', 'pub(crate) mod events {']
    for value in data['websocket']['events']:
        lines.append(f'    pub(crate) const {upper(value)}: &str = {rust_string(value)};')
    lines += ['}', '', 'pub(crate) mod messages {']
    for value in data['websocket']['messages']:
        lines.append(f'    pub(crate) const {upper(value)}: &str = {rust_string(value)};')
    lines += ['}', '', 'pub(crate) mod enums {']
    for enum_name, values in data['enums'].items():
        lines.append(f'    pub(crate) mod {enum_name} {{')
        for value in values:
            lines.append(f'        pub(crate) const {upper(value)}: &str = {rust_string(value)};')
        lines += ['    }']
    lines += ['}', '']
    return '\n'.join(lines + rust_constants(data['constants'])) + '\n'


def rust_constants(constants: dict) -> list[str]:
    lines = []
    rust_types = {
        'terminal_min_cols': 'u16',
        'terminal_max_cols': 'u16',
        'terminal_min_rows': 'u16',
        'terminal_max_rows': 'u16',
    }
    for name, value in constants.items():
        if isinstance(value, str):
            rust_type, rendered = '&str', rust_string(value)
        elif isinstance(value, bool):
            rust_type, rendered = 'bool', str(value).lower()
        else:
            rust_type, rendered = rust_types.get(name, 'u64'), str(value)
        lines.append(f'pub(crate) const {upper(name)}: {rust_type} = {rendered};')
    return lines


def csharp(data: dict) -> str:
    lines = [
        '// <auto-generated />',
        '// Source: shared/protocol.yaml. Regenerate with `just api-contract`.',
        'namespace SlopWorld',
        '{',
        '    internal static class WireProtocol',
        '    {',
        '        public const string TokenHeader = ' + cs_string(data['http']['headers']['token']) + ';',
        '        public const string SessionHeader = ' + cs_string(data['http']['headers']['session']) + ';',
        '        public const string WsPath = ' + cs_string(data['http']['websocket']['path']) + ';',
        '',
        '        internal static class Routes',
        '        {',
    ]
    for name, route in data['http']['routes'].items():
        lines.append(f'            public const string {pascal(name)} = {cs_string(route["path"])};')
    lines += ['        }', '', '        internal static class Events', '        {']
    for value in data['websocket']['events']:
        lines.append(f'            public const string {pascal(value)} = {cs_string(value)};')
    lines += ['        }', '', '        internal static class Messages', '        {']
    for value in data['websocket']['messages']:
        lines.append(f'            public const string {pascal(value)} = {cs_string(value)};')
    lines += ['        }', '']
    for enum_name, values in data['enums'].items():
        lines += [f'        internal static class {pascal(enum_name)}', '        {']
        for value in values:
            lines.append(f'            public const string {pascal(value)} = {cs_string(value)};')
        lines += ['        }', '']
    return '\n'.join(lines + cs_constants(data['constants']) + ['    }', '}', ''])


def cs_constants(constants: dict) -> list[str]:
    lines = []
    for name, value in constants.items():
        if isinstance(value, str):
            cs_type, rendered = 'string', cs_string(value)
        elif isinstance(value, bool):
            cs_type, rendered = 'bool', str(value).lower()
        else:
            cs_type, rendered = 'int', str(value)
        lines.append(f'        public const {cs_type} {pascal(name)} = {rendered};')
    return lines


def outputs(data: dict) -> dict[Path, str]:
    rust_dir = ROOT / 'slopd/src/shared'
    cs_dir = ROOT / 'mod/Source/SlopWorld/Client/Generated'
    return {
        rust_dir / 'protocol.rs': rust(data['protocol']),
        cs_dir / 'WireProtocol.cs': csharp(data['protocol']),
    }


def main() -> None:
    for path, content in outputs(load()).items():
        write_if_changed(path, content.encode())
        print(f'generated {path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
