id = "radio-paradise"
default_rate = 128

[metadata]
name = "RadioParadise Main"
donate = "https://radioparadise.com/donate"

[[stream]]
rate = 32
key = "mp3-32"
url = "https://stream.radioparadise.com/mp3-32"

[[stream]]
rate = 128
key = "mp3-128"
url = "https://stream.radioparadise.com/mp3-128"

[[stream]]
rate = 192
key = "mp3-192"
url = "https://stream.radioparadise.com/mp3-192"

[[stream]]
rate = 320
key = "mp3-320"
url = "https://stream.radioparadise.com/mp3-320"
