id = "somafm-groove-salad"
default_rate = 128

[metadata]
name = "SomaFM Groove Salad"
donate = ""

[[stream]]
rate = 128
key = "groovesalad-128-mp3"
url = "https://ice1.somafm.com/groovesalad-128-mp3"
