id = "somafm-secret-agent"
default_rate = 128

[metadata]
name = "SomaFM Secret Agent"
donate = ""

[[stream]]
rate = 128
key = "secretagent-128-mp3"
url = "https://ice1.somafm.com/secretagent-128-mp3"
