#!/usr/bin/env python3
"""Generate the mdBook API route inventory from the daemon router."""

from __future__ import annotations

from pathlib import Path

from reference import api_routes, read_files
import wire_contract


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs/src/reference/api-routes.md"


def render() -> str:
    payloads = {(method, route["path"]): types for route in wire_contract.load()["protocol"]["http"]["routes"].values() for method, types in route["protobuf"].items()}
    lines = [
        "<!-- Generated by tools/api_docs.py. Do not edit. -->",
        "# API route inventory",
        "",
        "Generated from `slopd/src/api/router.rs`. Scoped routes appear in the router that",
        "scoped grants can access. Handlers can require additional access.",
        "",
        "| Method | Path | Router scope | Handler | Request → response |",
        "| --- | --- | --- | --- | --- |",
    ]
    for route in api_routes(read_files()):
        lines.append(
            f"| `{route.method}` | `{route.path}` | `{route.scope}` | "
            f"`{route.handler}` | " + " → ".join(f"`{t}`" for t in payloads.get((route.method, route.path), ["ClientMessage", "Event"])) + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
