#!/usr/bin/env python3
"""Generate the mdBook API route inventory from the daemon router."""

from __future__ import annotations

from pathlib import Path

from reference import api_routes, read_files


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs/src/reference/api-routes.md"


def render() -> str:
    lines = [
        "<!-- Generated by tools/api_docs.py; do not edit. -->",
        "# API route inventory",
        "",
        "Generated from `slopd/src/api/router.rs`. `scoped` routes are mounted in the",
        "grant-visible router; handler guards can impose a stricter access requirement.",
        "",
        "| Method | Path | Router scope | Handler |",
        "| --- | --- | --- | --- |",
    ]
    for route in api_routes(read_files()):
        lines.append(
            f"| `{route.method}` | `{route.path}` | `{route.scope}` | "
            f"`{route.handler}` |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
