#!/usr/bin/env python3
"""Bake the text sprite atlas shared by UI labels and the terminal.

Unity's legacy IMGUI font path cannot draw Noto Color Emoji's CBDT/CBLC glyphs.
One Pango-rendered atlas supplies artwork without runtime emoji fonts. Generated
text keys map individual glyphs or explicitly supplied sequences to sprite slots.
"""

import argparse
import importlib.util
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EMOJI_TOOL = os.path.join(HERE, "emoji.py")
DEFAULT_TEXTURE = os.path.join(ROOT, "mod", "Textures", "SlopWorld", "TerminalEmoji.png")
DEFAULT_DATA = os.path.join(ROOT, "mod", "Source", "SlopWorld", "UI", "Text", "TextSpriteData.cs")

SIZE = 32
PROBE = 256
COLUMNS = 32
BREATHE = 1.08


def load_emoji_tool():
    spec = importlib.util.spec_from_file_location("slopworld_emoji", EMOJI_TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def font_codepoints():
    raw = subprocess.check_output(
        ["fc-query", "--format=%{charset}\\n", "/usr/share/fonts/noto/NotoColorEmoji.ttf"],
        text=True,
    )
    result = []
    for token in raw.split():
        bounds = token.split("-")
        first = int(bounds[0], 16)
        last = int(bounds[-1], 16)
        result.extend(range(first, last + 1))
    return sorted(set(cp for cp in result if 0x10000 <= cp <= 0x10FFFF))


def bake_one(rendered):
    import numpy as np
    from PIL import Image

    alpha = rendered[..., 3]
    ys, xs = np.nonzero(alpha > 10 / 255.0)
    if len(ys) == 0:
        return None

    cy, cx = (ys.min() + ys.max()) / 2, (xs.min() + xs.max()) / 2
    side = int(max(ys.max() - ys.min(), xs.max() - xs.min()) * BREATHE)
    side = max(1, min(side, PROBE))
    y0 = max(0, int(cy - side / 2))
    x0 = max(0, int(cx - side / 2))
    if y0 + side > PROBE:
        y0 = PROBE - side
    if x0 + side > PROBE:
        x0 = PROBE - side
    crop = rendered[y0:y0 + side, x0:x0 + side]

    edge = max(crop.shape[:2])
    padded = np.zeros((edge, edge, 4), dtype=np.float32)
    py, px = (edge - crop.shape[0]) // 2, (edge - crop.shape[1]) // 2
    padded[py:py + crop.shape[0], px:px + crop.shape[1]] = crop
    return Image.fromarray(
        np.clip(padded * 255 + 0.5, 0, 255).astype(np.uint8), "RGBA"
    ).resize((SIZE, SIZE), Image.Resampling.LANCZOS)


def write_data(path, keys, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    values = ", ".join('"' + "".join(f"\\U{ord(c):08X}" for c in key) + '"' for key in keys)
    source = f'''// Generated by tools/emoji_atlas.py; do not edit by hand.
namespace SlopWorld
{{
    static class TextSpriteData
    {{
        public const int AtlasColumns = {COLUMNS};
        public const int AtlasRows = {rows};
        public static readonly string[] Keys = new string[] {{ {values} }};
    }}
}}
'''
    with open(path, "w", encoding="utf-8", newline="\n") as stream:
        stream.write(source)


def main():
    from PIL import Image

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--texture", default=DEFAULT_TEXTURE)
    parser.add_argument("--data", default=DEFAULT_DATA)
    parser.add_argument("--sequences", help="UTF-8 file of additional sprite text keys, one per line")
    args = parser.parse_args()

    emoji_tool = load_emoji_tool()
    keys = [chr(cp) for cp in font_codepoints()]
    if args.sequences:
        with open(args.sequences, encoding="utf-8") as stream:
            keys.extend(line.rstrip("\r\n") for line in stream if line.strip())
    keys = list(dict.fromkeys(keys))
    cells = []
    for index, key in enumerate(keys, 1):
        if index % 100 == 0:
            print(f"rendered {index}/{len(keys)}", flush=True)
        try:
            cell = bake_one(emoji_tool.render(key, PROBE))
        except Exception as error:
            raise RuntimeError(f"cannot bake sprite {key!r}") from error
        if cell is not None:
            cells.append((key, cell))

    rows = (len(cells) + COLUMNS - 1) // COLUMNS
    atlas = Image.new("RGBA", (COLUMNS * SIZE, max(1, rows) * SIZE), (0, 0, 0, 0))
    for slot, (_key, cell) in enumerate(cells):
        atlas.paste(cell, ((slot % COLUMNS) * SIZE, (slot // COLUMNS) * SIZE))

    os.makedirs(os.path.dirname(args.texture), exist_ok=True)
    atlas.save(args.texture, optimize=True)
    write_data(args.data, [key for key, _cell in cells], max(1, rows))
    print(f"wrote {len(cells)} emoji cells to {args.texture}")


if __name__ == "__main__":
    main()
