#!/usr/bin/env python3
"""Generate CLI and test adapters from the route payload inventory. IPC carries no JSON text."""
from pathlib import Path
import json
import re
import subprocess

import yaml

ROOT = Path(__file__).resolve().parents[1]
protocol = yaml.safe_load((ROOT / 'shared/protocol.yaml').read_text())
schema = set(re.findall(r'message (\w+) \{', (ROOT / 'shared/slopworld.proto').read_text()))
rows = []
for name, route in protocol['http']['routes'].items():
    assert set(route['protobuf']) == set(route['methods']), name
    for method, (request, response) in route['protobuf'].items():
        assert request in schema and response in schema, name
        rows.append((method, route['path'], request, response))

# Static routes must win over parameter routes of equal depth. Keep this order in
# the single lookup table so every adapter uses the same route selection.
rows.sort(key=lambda row: row[1].count(':'))
request_kinds = sorted({row[2] for row in rows})
response_kinds = sorted({row[3] for row in rows})

out = [
    '// Generated by tools/protobuf_http.py. Do not edit.',
    '#![allow(',
    '    dead_code,',
    '    reason = "generated route adapters are shared across daemon and mod clients"',
    ')]',
    'use super::wire;',
    'use prost::Message;',
    'use serde_json::Value;',
    'fn encode_wire<T>(value: Value) -> anyhow::Result<Vec<u8>>',
    'where',
    '    T: serde::de::DeserializeOwned + Message,',
    '{',
    '    Ok(serde_json::from_value::<T>(value)?.encode_to_vec())',
    '}',
    'pub(crate) const CONTENT_TYPE: &str = "application/x-protobuf";',
    'fn matches(pattern: &str, path: &str) -> bool {',
    "    let path = path.split('?').next().unwrap_or(path);",
    "    let a: Vec<_> = pattern.split('/').collect();",
    "    let b: Vec<_> = path.split('/').collect();",
    "    a.len() == b.len() && a.iter().zip(b).all(|(a,b)| a.starts_with(':') || *a == b)",
    '}',
    '#[derive(Clone, Copy)]',
    'enum RequestKind {',
]
out.extend(f'    {kind},' for kind in request_kinds)
out.extend(['}', '#[derive(Clone, Copy)]', 'enum ResponseKind {'])
out.extend(f'    {kind},' for kind in response_kinds)
out.extend([
    '}',
    # Short aliases keep generated route rows compact.
    'use RequestKind as Req;',
    'use ResponseKind as Resp;',
    "type Route = (&'static str, RequestKind, ResponseKind);",
    'const ROUTES: &[Route] = &[',
])
for method, path, request, response in rows:
    route_key = json.dumps(f'{method} {path}')
    out.append(f'    ({route_key}, Req::{request}, Resp::{response}),')
out.extend([
    '];',
    'fn route(method: &str, path: &str) -> anyhow::Result<&\'static Route> {',
    '    ROUTES',
    '        .iter()',
    "        .find(|route| match route.0.split_once(' ') {",
    '            Some((route_method, route_path)) => {',
    '                route_method == method && matches(route_path, path)',
    '            }',
    '            None => false,',
    '        })',
    '        .ok_or_else(|| anyhow::anyhow!("unknown Protobuf route: {method} {path}"))',
    '}',
])


def emit_dispatch(name, kind_index, kind_name, kinds, input_type, output_type, encode, test_only=False):
    if test_only:
        out.append('#[cfg(test)]')
    out.append(
        f'pub(crate) fn {name}(method: &str, path: &str, value: {input_type}) '
        f'-> anyhow::Result<{output_type}> {{'
    )
    out.append('    let route = route(method, path)?;')
    out.append(f'    match route.{kind_index} {{')
    for kind in kinds:
        if encode:
            expression = f'encode_wire::<wire::{kind}>(value)'
        else:
            expression = f'serde_json::to_value(wire::{kind}::decode(value)?)?'
        if encode:
            out.append(f'        {kind_name}Kind::{kind} => {expression},')
        else:
            out.append(f'        {kind_name}Kind::{kind} => Ok({expression}),')
    out.extend(['    }', '}'])


emit_dispatch('encode_request', '1', 'Request', request_kinds, 'Value', 'Vec<u8>', True)
emit_dispatch('decode_response', '2', 'Response', response_kinds, '&[u8]', 'Value', False)
emit_dispatch('decode_request', '1', 'Request', request_kinds, '&[u8]', 'Value', False, True)
emit_dispatch('encode_response', '2', 'Response', response_kinds, 'Value', 'Vec<u8>', True, True)

(ROOT / 'slopd/src/shared/http_wire.rs').write_text('\n'.join(out) + '\n')
subprocess.run(['rustfmt', '--edition', '2024', str(ROOT / 'slopd/src/shared/http_wire.rs')], check=True)
