#!/usr/bin/env python3
"""Generate CLI and test adapters from the route payload inventory. IPC carries no JSON text."""
from pathlib import Path
import re
import subprocess
import yaml
ROOT = Path(__file__).resolve().parents[1]
protocol = yaml.safe_load((ROOT / 'shared/protocol.yaml').read_text())
schema = set(re.findall(r'message (\w+) \{', (ROOT / 'shared/slopworld.proto').read_text()))
rows = []
for name, route in protocol['http']['routes'].items():
    assert set(route['protobuf']) == set(route['methods']), name
    for method, (request, response) in route['protobuf'].items():
        assert request in schema and response in schema, name
        rows.append((method, route['path'], request, response))
# Static routes must win over parameter routes of equal depth.
rows.sort(key=lambda r: r[1].count(':'))
out = ['// Generated by tools/protobuf_http.py. Do not edit.', '#![allow(dead_code)]',
       'use super::wire;', 'use prost::Message;', 'use serde_json::Value;',
       'pub(crate) const CONTENT_TYPE: &str = "application/x-protobuf";',
       'fn matches(pattern: &str, path: &str) -> bool {',
       '    let path = path.split(\'?\').next().unwrap_or(path);',
       '    let a: Vec<_> = pattern.split(\'/\').collect();',
       '    let b: Vec<_> = path.split(\'/\').collect();',
       '    a.len() == b.len() && a.iter().zip(b).all(|(a,b)| a.starts_with(\':\') || *a == b)', '}']
for direction in ['encode_request', 'decode_response', 'decode_request', 'encode_response']:
    encode = direction.startswith('encode')
    request = direction.endswith('request')
    if direction in ['decode_request', 'encode_response']: out.append('#[cfg(test)]')
    out.append(f'pub(crate) fn {direction}(method: &str, path: &str, value: '+('Value' if encode else '&[u8]')+') -> anyhow::Result<'+('Vec<u8>' if encode else 'Value')+'> {')
    for method,path,req,resp in rows:
        ty = req if request else resp
        expr = f'serde_json::from_value::<wire::{ty}>(value)?.encode_to_vec()' if encode else f'serde_json::to_value(wire::{ty}::decode(value)?)?'
        out.append(f'    if method == "{method}" && matches("{path}", path) {{ return Ok({expr}); }}')
    out.extend(['    anyhow::bail!("unknown Protobuf route: {method} {path}")', '}'])
(ROOT / 'slopd/src/shared/http_wire.rs').write_text('\n'.join(out)+'\n')

subprocess.run(["rustfmt", "--edition", "2021", str(ROOT / "slopd/src/shared/http_wire.rs")], check=True)
