#!/usr/bin/env python3
"""Generate Rust and C# bindings from the shared wire contract."""

from __future__ import annotations

import re
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - exercised by a missing developer dependency
    raise SystemExit(
        "make api-contract requires PyYAML; install it with: python3 -m pip install PyYAML"
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "protocol" / "wire.yaml"
RUST_OUT = ROOT / "slopd" / "src" / "wire.rs"
CS_OUT = ROOT / "mod" / "Source" / "SlopWorld" / "Client" / "Generated" / "WireContract.cs"


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_-]+", name))


def upper(name: str) -> str:
    return name.upper().replace("-", "_")


def load() -> dict:
    data = yaml.safe_load(CONTRACT.read_text())
    if data.get("version") != 1:
        raise SystemExit("unsupported protocol contract version")
    if not data.get("http", {}).get("routes"):
        raise SystemExit("protocol contract has no HTTP routes")
    return data


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cs_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust(data: dict) -> str:
    lines = [
        "// <auto-generated />",
        "// Source: protocol/wire.yaml; regenerate with `make api-contract`.",
        "#![allow(dead_code)]",
        "",
        "#[macro_export]",
        "macro_rules! wire_enum {",
        "    ($ty:ty, { $($variant:path => $value:path),+ $(,)? }) => {",
        "        impl serde::Serialize for $ty {",
        "            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>",
        "            where S: serde::Serializer {",
        "                let value = match self {",
        "                    $($variant => $value,)+",
        "                };",
        "                serializer.serialize_str(value)",
        "            }",
        "        }",
        "        impl<'de> serde::Deserialize<'de> for $ty {",
        "            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>",
        "            where D: serde::Deserializer<'de> {",
        "                let value = <String as serde::Deserialize>::deserialize(deserializer)?;",
        "                $(if value == $value { return Ok($variant); })+",
        "                Err(<D::Error as serde::de::Error>::unknown_variant(&value, &[]))",
        "            }",
        "        }",
        "    };",
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_event_tag {",
    ]
    for value in data["websocket"]["events"]:
        lines += [
            f"    ({pascal(value)}) => {{",
            f"        $crate::wire::events::{upper(value)}",
            "    };",
        ]
    lines += [
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_event_serialize {",
        "    ($ty:ty, { $( $variant:ident { $( $field:ident ),+ $(,)? } ),+ $(,)? }) => {",
        "        impl serde::Serialize for $ty {",
        "            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>",
        "            where S: serde::Serializer {",
        "                use serde::ser::SerializeStruct;",
        "                let mut out = serializer.serialize_struct(stringify!($ty), 2)?;",
        "                match self {",
        "                    $(Self::$variant { $( $field ),+ } => {",
        "                        out.serialize_field(\"t\", $crate::wire_event_tag!($variant))?;",
        "                        $(out.serialize_field(stringify!($field), $field)?;)+",
        "                    }),+",
        "                }",
        "                out.end()",
        "            }",
        "        }",
        "    };",
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_client_msg_tag {",
    ]
    for value in data["websocket"]["messages"]:
        lines += [
            f"    ({pascal(value)}) => {{",
            f"        $crate::wire::messages::{upper(value)}",
            "    };",
        ]
    lines += [
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_client_msg_payload {",
        "    ($value:ident, strip_tag) => {{",
        "        let mut payload = $value;",
        "        payload",
        "            .as_object_mut()",
        "            .expect(\"websocket message tag came from a JSON object\")",
        "            .remove(\"t\");",
        "        payload",
        "    }};",
        "    ($value:ident) => {",
        "        $value",
        "    };",
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_client_msg_construct {",
        "    ($variant:ident, $req:ident, { $( $field:ident ),+ $(,)? }) => {",
        "        Self::$variant { $( $field: $req.$field ),+ }",
        "    };",
        "    ($variant:ident, $req:ident) => { Self::$variant($req) };",
        "}",
        "",
        "#[macro_export]",
        "macro_rules! wire_client_msg_deserialize {",
        "    (",
        "        $ty:ty, {",
        "            $(",
        "                $variant:ident",
        "                $( { $( $field:ident ),+ $(,)? } )?",
        "                => $payload:ty $( [ $mode:ident ] )?",
        "            ),+ $(,)?",
        "        }",
        "    ) => {",
        "        impl<'de> serde::Deserialize<'de> for $ty {",
        "            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>",
        "            where D: serde::Deserializer<'de> {",
        "                use serde::de::Error;",
        "                let value = serde_json::Value::deserialize(deserializer)?;",
        "                let tag = value",
        "                    .get(\"t\")",
        "                    .and_then(serde_json::Value::as_str)",
        "                    .ok_or_else(|| D::Error::custom(\"websocket message is missing tag t\"))?;",
        "                match tag {",
        "                    $( $crate::wire_client_msg_tag!($variant) => {",
        "                        let req: $payload = serde_json::from_value(",
        "                            $crate::wire_client_msg_payload!(value $(, $mode)?)",
        "                        )",
        "                        .map_err(D::Error::custom)?;",
        "                        Ok($crate::wire_client_msg_construct!($variant, req $(, { $( $field ),+ })?))",
        "                    }),+",
        "                    other => Err(D::Error::unknown_variant(other, &[])),",
        "                }",
        "            }",
        "        }",
        "    };",
        "}",
        "",
        "pub(crate) const TOKEN_HEADER: &str = "
        + rust_string(data["http"]["headers"]["token"])
        + ";",
        "pub(crate) const SESSION_HEADER: &str = "
        + rust_string(data["http"]["headers"]["session"])
        + ";",
        "pub(crate) const WS_PATH: &str = "
        + rust_string(data["http"]["websocket"]["path"])
        + ";",
        "",
        "pub(crate) mod routes {",
    ]
    for name, route in data["http"]["routes"].items():
        lines.append(f"    pub(crate) const {upper(name)}: &str = {rust_string(route['path'])};")
    lines += ["}", "", "pub(crate) mod events {"]
    for value in data["websocket"]["events"]:
        lines.append(f"    pub(crate) const {upper(value)}: &str = {rust_string(value)};")
    lines += ["}", "", "pub(crate) mod messages {"]
    for value in data["websocket"]["messages"]:
        lines.append(f"    pub(crate) const {upper(value)}: &str = {rust_string(value)};")
    lines += ["}", "", "pub(crate) mod enums {"]
    for enum_name, values in data["enums"].items():
        lines.append(f"    pub(crate) mod {enum_name} {{")
        for value in values:
            lines.append(f"        pub(crate) const {upper(value)}: &str = {rust_string(value)};")
        lines += ["    }"]
    lines += ["}", "", "pub(crate) mod usage {"]
    for name, item in data["usage"]["keys"].items():
        lines.append(f"    pub(crate) const {upper(name)}: &str = {rust_string(name)};")
    lines += ["}", ""]
    rust_types = {
        "endpoint_port": "u16",
        "scrollback_lines": "u32",
        "terminal_min_cols": "u16",
        "terminal_max_cols": "u16",
        "terminal_min_rows": "u16",
        "terminal_max_rows": "u16",
        "usage_poll_secs": "u64",
    }
    for name, value in data["constants"].items():
        if isinstance(value, str):
            rust_type, rendered = "&str", rust_string(value)
        elif isinstance(value, bool):
            rust_type, rendered = "bool", str(value).lower()
        else:
            rust_type, rendered = rust_types.get(name, "u64"), str(value)
        lines.append(f"pub(crate) const {upper(name)}: {rust_type} = {rendered};")
    endpoint = data["constants"]
    lines.append(
        f"pub(crate) const DEFAULT_BIND: &str = {rust_string(endpoint['endpoint_host'] + ':' + str(endpoint['endpoint_port']))};"
    )
    return "\n".join(lines) + "\n"


def csharp(data: dict) -> str:
    lines = [
        "// <auto-generated />",
        "// Source: protocol/wire.yaml; regenerate with `make api-contract`.",
        "namespace SlopWorld",
        "{",
        "    internal static class WireContract",
        "    {",
        "        public const string TokenHeader = "
        + cs_string(data["http"]["headers"]["token"])
        + ";",
        "        public const string SessionHeader = "
        + cs_string(data["http"]["headers"]["session"])
        + ";",
        "        public const string WsPath = "
        + cs_string(data["http"]["websocket"]["path"])
        + ";",
        "",
        "        internal static class Routes",
        "        {",
    ]
    for name, route in data["http"]["routes"].items():
        lines.append(f"            public const string {pascal(name)} = {cs_string(route['path'])};")
    lines += ["        }", "", "        internal static class Events", "        {"]
    for value in data["websocket"]["events"]:
        lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
    lines += ["        }", "", "        internal static class Messages", "        {"]
    for value in data["websocket"]["messages"]:
        lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
    lines += ["        }", ""]
    for enum_name, values in data["enums"].items():
        lines += [f"        internal static class {pascal(enum_name)}", "        {"]
        for value in values:
            lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
        lines += ["        }", ""]
    lines += ["        internal static class UsageKeys", "        {"]
    for name in data["usage"]["keys"]:
        lines.append(f"            public const string {pascal(name)} = {cs_string(name)};")
    lines += ["        }", ""]
    for name, value in data["constants"].items():
        if isinstance(value, str):
            cs_type, rendered = "string", cs_string(value)
        elif isinstance(value, bool):
            cs_type, rendered = "bool", str(value).lower()
        else:
            cs_type, rendered = "int", str(value)
        lines.append(f"        public const {cs_type} {pascal(name)} = {rendered};")
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def main() -> None:
    data = load()
    RUST_OUT.write_text(rust(data))
    CS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CS_OUT.write_text(csharp(data))
    print(f"generated {RUST_OUT.relative_to(ROOT)}")
    print(f"generated {CS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
