#!/usr/bin/env python3
"""Generate Rust and C# bindings from the shared wire protocol only.

Daemon defaults and usage policy belong to their Rust owners. They are exposed as API read
models; keeping them out of generated client bindings prevents a stale mod from becoming a
second policy implementation.
"""

from __future__ import annotations

import re
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - exercised by a missing developer dependency
    raise SystemExit(
        "make api-contract requires PyYAML; install it with: python3 -m pip install PyYAML"
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
SHARED = ROOT / "shared"


def rust_header(source: str) -> list[str]:
    return [
        "// <auto-generated />",
        f"// Source: shared/{source}.yaml; regenerate with `make api-contract`.",
        "#![allow(dead_code)]", "",
    ]


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_-]+", name))


def upper(name: str) -> str:
    return name.upper().replace("-", "_")


class UniqueLoader(yaml.SafeLoader):
    """Reject duplicate keys instead of silently replacing shared definitions."""


def unique_mapping(loader, node):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node)
        if key in result:
            raise ValueError(f"duplicate key {key!r} at {key_node.start_mark}")
        result[key] = loader.construct_object(value_node)
    return result


UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping)


def load(directory: Path = SHARED) -> dict:
    data = {}
    expected = {"version", "http", "websocket", "enums", "constants"}
    path = directory / "protocol.yaml"
    document = yaml.load(path.read_text(), Loader=UniqueLoader)
    if not isinstance(document, dict) or set(document) != expected:
        raise ValueError(f"{path}: expected sections {sorted(expected)}")
    if type(document["version"]) is not int or document["version"] != 2:
        raise ValueError(f"{path}: unsupported shared definition version")
    for section in expected - {"version"}:
        if not isinstance(document[section], dict) or not document[section]:
            raise ValueError(f"{path}: {section} must be a nonempty mapping")
    data["protocol"] = document
    validate(data)
    return data


def validate(data: dict) -> None:
    protocol = data["protocol"]
    routes = protocol["http"].get("routes")
    if not isinstance(routes, dict) or not routes:
        raise ValueError("protocol definition has no HTTP routes")
    for name, route in routes.items():
        if (not isinstance(route["path"], str) or not route["path"].startswith("/")
                or not isinstance(route["methods"], list) or not route["methods"]
                or any(m not in {"GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "TRACE"} for m in route["methods"])
                or route["scope"] not in {"root", "scoped"}):
            raise ValueError(f"invalid route {name}")
    for name, values in {**protocol["websocket"], **protocol["enums"]}.items():
        if (not isinstance(values, list) or not values
                or any(not isinstance(v, str) for v in values) or len(values) != len(set(values))):
            raise ValueError(f"{name}: expected unique string values")
    for name, value in protocol["constants"].items():
        if type(value) not in (str, bool, int):
            raise ValueError(f"protocol.{name}: expected string, boolean or integer")


def rust_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def cs_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def rust(data: dict) -> str:
    lines = rust_header("protocol")
    for macro, section in (("wire_event_tag", "events"), ("wire_client_msg_tag", "messages")):
        lines += ["#[macro_export]", f"macro_rules! {macro} {{"]
        for value in data["websocket"][section]:
            lines += [
                f"    ({pascal(value)}) => {{",
                f"        $crate::shared::protocol::{section}::{upper(value)}",
                "    };",
            ]
        lines += ["}", ""]
    lines += [
        "pub(crate) const TOKEN_HEADER: &str = "
        + rust_string(data["http"]["headers"]["token"])
        + ";",
        "pub(crate) const SESSION_HEADER: &str = "
        + rust_string(data["http"]["headers"]["session"])
        + ";",
        "pub(crate) const WS_PATH: &str = "
        + rust_string(data["http"]["websocket"]["path"])
        + ";",
        "",
        "pub(crate) mod routes {",
    ]
    for name, route in data["http"]["routes"].items():
        lines.append(f"    pub(crate) const {upper(name)}: &str = {rust_string(route['path'])};")
    lines += ["}", "", "pub(crate) mod events {"]
    for value in data["websocket"]["events"]:
        lines.append(f"    pub(crate) const {upper(value)}: &str = {rust_string(value)};")
    lines += ["}", "", "pub(crate) mod messages {"]
    for value in data["websocket"]["messages"]:
        lines.append(f"    pub(crate) const {upper(value)}: &str = {rust_string(value)};")
    lines += ["}", "", "pub(crate) mod enums {"]
    for enum_name, values in data["enums"].items():
        lines.append(f"    pub(crate) mod {enum_name} {{")
        for value in values:
            lines.append(f"        pub(crate) const {upper(value)}: &str = {rust_string(value)};")
        lines += ["    }"]
    lines += ["}", ""]
    return "\n".join(lines + rust_constants(data["constants"])) + "\n"


def rust_constants(constants: dict) -> list[str]:
    lines = []
    rust_types = {
        "terminal_min_cols": "u16",
        "terminal_max_cols": "u16",
        "terminal_min_rows": "u16",
        "terminal_max_rows": "u16",
    }
    for name, value in constants.items():
        if isinstance(value, str):
            rust_type, rendered = "&str", rust_string(value)
        elif isinstance(value, bool):
            rust_type, rendered = "bool", str(value).lower()
        else:
            rust_type, rendered = rust_types.get(name, "u64"), str(value)
        lines.append(f"pub(crate) const {upper(name)}: {rust_type} = {rendered};")
    return lines


def csharp(data: dict) -> str:
    lines = [
        "// <auto-generated />",
        "// Source: shared/protocol.yaml; regenerate with `make api-contract`.",
        "namespace SlopWorld",
        "{",
        "    internal static class WireProtocol",
        "    {",
        "        public const string TokenHeader = "
        + cs_string(data["http"]["headers"]["token"])
        + ";",
        "        public const string SessionHeader = "
        + cs_string(data["http"]["headers"]["session"])
        + ";",
        "        public const string WsPath = "
        + cs_string(data["http"]["websocket"]["path"])
        + ";",
        "",
        "        internal static class Routes",
        "        {",
    ]
    for name, route in data["http"]["routes"].items():
        lines.append(f"            public const string {pascal(name)} = {cs_string(route['path'])};")
    lines += ["        }", "", "        internal static class Events", "        {"]
    for value in data["websocket"]["events"]:
        lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
    lines += ["        }", "", "        internal static class Messages", "        {"]
    for value in data["websocket"]["messages"]:
        lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
    lines += ["        }", ""]
    for enum_name, values in data["enums"].items():
        lines += [f"        internal static class {pascal(enum_name)}", "        {"]
        for value in values:
            lines.append(f"            public const string {pascal(value)} = {cs_string(value)};")
        lines += ["        }", ""]
    return "\n".join(lines + cs_constants(data["constants"]) + ["    }", "}", ""])


def cs_constants(constants: dict) -> list[str]:
    lines = []
    for name, value in constants.items():
        if isinstance(value, str):
            cs_type, rendered = "string", cs_string(value)
        elif isinstance(value, bool):
            cs_type, rendered = "bool", str(value).lower()
        else:
            cs_type, rendered = "int", str(value)
        lines.append(f"        public const {cs_type} {pascal(name)} = {rendered};")
    return lines


def outputs(data: dict) -> dict[Path, str]:
    rust_dir = ROOT / "slopd/src/shared"
    cs_dir = ROOT / "mod/Source/SlopWorld/Client/Generated"
    return {
        rust_dir / "protocol.rs": rust(data["protocol"]),
        cs_dir / "WireProtocol.cs": csharp(data["protocol"]),
    }


def main() -> None:
    for path, content in outputs(load()).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"generated {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
